/*
 * bau-katalog.js – Was es in der Bauecke gibt: Häuser, Zimmer, Farben, Tiere
 * und ihre Wünsche.
 * ---------------------------------------------------------------------------
 * Vier Häuser stehen nebeneinander an der Strasse: das Wohnhaus, das Spital,
 * das Dorfzentrum und das Bürohaus. Jedes wächst Stockwerk um Stockwerk, und
 * jedes Stockwerk ist ein Zimmer, dessen Art das Kind wählt. Zu jeder Art
 * gehört ein kurzer Satz, der erklärt, was dort geschieht – im Spital lernt
 * ein Kind so ganz nebenbei, was eine Radiologie ist.
 *
 * In jedem Stockwerk wohnt (oder arbeitet) ein Tier. Es hat Wünsche:
 *   gelb   fünf für sein eigenes Zimmer – ein Bett, eine Lampe, eine Farbe
 *   grün   zwei für sein Haus – "Im Wohnhaus wünsche ich mir ein Badezimmer"
 *   blau   einen für ein anderes Haus – "Im Dorfzentrum wünsche ich mir einen
 *          Spielplatz"; so brauchen die vier Häuser einander
 * Wer welche Wünsche hat, rechnet bau-stand.js aus diesen Listen aus.
 *
 * Nur Daten, keine Logik: Die Prüfung scripts/validate-bau.mjs liest diese
 * Datei ohne Browser und hält sie mit bau-moebel.js stimmig – jeder Wunsch
 * muss sich mit einem Ding erfüllen lassen, jedes Zimmer genug Wünsche haben.
 */
(() => {
  "use strict";

  // ---------------------------------------------------------------------------
  // Farben
  // ---------------------------------------------------------------------------
  // Eine Palette für Wände, Böden, Fassaden und Möbel. familie fasst Töne
  // zusammen, damit "Ich mag Blau" auch mit Hellblau erfüllt ist; wort ist,
  // wie die Farbe im Satz heisst ("Malst du die Wand blau an?").
  const FARBEN = [
    { id: "weiss", name: "Weiss", hex: "#fbf8f2", familie: "weiss" },
    { id: "creme", name: "Creme", hex: "#f6ead2", familie: "weiss" },
    { id: "hellgelb", name: "Hellgelb", hex: "#fff1b8", familie: "gelb" },
    { id: "gelb", name: "Gelb", hex: "#ffd166", familie: "gelb" },
    { id: "pfirsich", name: "Pfirsich", hex: "#ffd3b5", familie: "orange" },
    { id: "orange", name: "Orange", hex: "#ff9f43", familie: "orange" },
    { id: "rot", name: "Rot", hex: "#ef5350", familie: "rot" },
    { id: "rosa", name: "Rosa", hex: "#ffc4d6", familie: "rosa" },
    { id: "pink", name: "Pink", hex: "#ff6fa5", familie: "rosa" },
    { id: "flieder", name: "Flieder", hex: "#e3d8ff", familie: "violett" },
    { id: "violett", name: "Violett", hex: "#a78bfa", familie: "violett" },
    { id: "hellblau", name: "Hellblau", hex: "#cfeaff", familie: "blau" },
    { id: "blau", name: "Blau", hex: "#4f8ef7", familie: "blau" },
    { id: "dunkelblau", name: "Dunkelblau", hex: "#34508f", familie: "blau" },
    { id: "tuerkis", name: "Türkis", hex: "#3cc8c8", familie: "tuerkis" },
    { id: "mint", name: "Mint", hex: "#c9f2e2", familie: "gruen" },
    { id: "hellgruen", name: "Hellgrün", hex: "#c5ec9a", familie: "gruen" },
    { id: "gruen", name: "Grün", hex: "#5cbf62", familie: "gruen" },
    { id: "dunkelgruen", name: "Dunkelgrün", hex: "#2f7d4f", familie: "gruen" },
    { id: "beige", name: "Beige", hex: "#e2c9a6", familie: "braun" },
    { id: "braun", name: "Braun", hex: "#a0704a", familie: "braun" },
    { id: "hellgrau", name: "Hellgrau", hex: "#e2e7ee", familie: "grau" },
    { id: "grau", name: "Grau", hex: "#9aa5b1", familie: "grau" },
    { id: "schwarz", name: "Schwarz", hex: "#3a4250", familie: "schwarz" },
  ];
  const FARBE = Object.fromEntries(FARBEN.map((farbe) => [farbe.id, farbe]));

  // Die Familien, die sich ein Tier wünschen kann, und wie sie im Satz heissen.
  const FAMILIEN = {
    gelb: { name: "Gelb", wort: "gelb", zeige: "gelb" },
    orange: { name: "Orange", wort: "orange", zeige: "orange" },
    rot: { name: "Rot", wort: "rot", zeige: "rot" },
    rosa: { name: "Rosa", wort: "rosa", zeige: "rosa" },
    violett: { name: "Violett", wort: "violett", zeige: "violett" },
    blau: { name: "Blau", wort: "blau", zeige: "blau" },
    tuerkis: { name: "Türkis", wort: "türkis", zeige: "tuerkis" },
    gruen: { name: "Grün", wort: "grün", zeige: "gruen" },
    braun: { name: "Braun", wort: "braun", zeige: "braun" },
  };

  // Muster für die Wand. Gezeichnet werden sie in bau-art.js, aus der
  // Wandfarbe abgeleitet – eine Farbe, ein Muster, und es passt.
  const MUSTER = [
    { id: "keine", name: "Ohne Muster" },
    { id: "streifen", name: "Streifen" },
    { id: "punkte", name: "Punkte" },
    { id: "karos", name: "Karos" },
    { id: "sterne", name: "Sterne" },
    { id: "herzen", name: "Herzen" },
    { id: "blumen", name: "Blumen" },
    { id: "wellen", name: "Wellen" },
    { id: "ziegel", name: "Backstein" },
    { id: "holz", name: "Holz" },
    { id: "kacheln", name: "Kacheln" },
  ];

  // Böden. farbe ist der Grundton; das Kind kann ihn aus der Palette ändern.
  const BOEDEN = [
    { id: "parkett", name: "Parkett", farbe: "#c88c5c" },
    { id: "dielen", name: "Holzdielen", farbe: "#d9a066" },
    { id: "plaettli", name: "Plättli", farbe: "#e2e7ee" },
    { id: "teppichboden", name: "Teppichboden", farbe: "#a78bfa" },
    { id: "stein", name: "Steinboden", farbe: "#b9b2a7" },
    { id: "linoleum", name: "Linoleum", farbe: "#6cc3d5" },
    { id: "rasen", name: "Rasen", farbe: "#5cbf62" },
  ];
  const BODEN = Object.fromEntries(BOEDEN.map((boden) => [boden.id, boden]));

  // ---------------------------------------------------------------------------
  // Die vier Häuser
  // ---------------------------------------------------------------------------
  // im: "im Wohnhaus" – für die Wünsche. dach: wie das Dach aussieht.
  const HAEUSER = [
    { id: "wohnhaus", name: "Wohnhaus", der: "das Wohnhaus", im: "im Wohnhaus", fassade: "pfirsich", dach: "rot", dachForm: "giebel",
      text: "Im Wohnhaus wohnen die Tiere: mit Schlafzimmer, Küche, Badezimmer und allem, was man zum Wohnen braucht." },
    { id: "spital", name: "Spital", der: "das Spital", im: "im Spital", fassade: "weiss", dach: "blau", dachForm: "heli",
      text: "Im Spital wird geholfen, wenn jemand krank ist oder sich verletzt hat. Jede Abteilung hat ihre eigene Aufgabe." },
    { id: "zentrum", name: "Dorfzentrum", der: "das Dorfzentrum", im: "im Dorfzentrum", fassade: "hellgelb", dach: "gruen", dachForm: "turm",
      text: "Im Dorfzentrum trifft man sich: zum Einkaufen, Lesen, Essen, Spielen und Schwimmen." },
    { id: "buero", name: "Bürohaus", der: "das Bürohaus", im: "im Bürohaus", fassade: "hellblau", dach: "grau", dachForm: "flach",
      text: "Im Bürohaus wird gearbeitet: an Schreibtischen, in Sitzungen und am Computer." },
  ];
  const HAUS = Object.fromEntries(HAEUSER.map((haus) => [haus.id, haus]));

  // ---------------------------------------------------------------------------
  // Die Zimmer
  // ---------------------------------------------------------------------------
  // der/ein:  mit Artikel, für die Sätze ("das Badezimmer", "ein Badezimmer")
  // text:     was hier geschieht – das liest die Stimme vor, wenn das Kind die
  //           Zimmerart antippt
  // wand/muster/boden: wie das Zimmer am Anfang aussieht
  // icon:     ein Ding, das für das Zimmer steht (Karten, Wünsche)
  // passend:  was in der ersten Schublade ("Passt hier") liegt
  // wuensche: woraus die gelben Wünsche des Tiers gezogen werden (tags)
  // arbeit:   hier arbeiten Tiere aus dem Wohnhaus manchmal
  // ausflug:  hierhin gehen Tiere aus dem Wohnhaus in der Freizeit
  const R = (id, haus, name, der, ein, text, opts) => ({ id, haus, name, der, ein, text, muster: "keine", boden: "parkett", ...opts });

  const RAEUME_LISTE = [
    // --- Wohnhaus -------------------------------------------------------------
    R("eingang", "wohnhaus", "Eingang", "der Eingang", "einen Eingang",
      "Beim Eingang kommt man ins Haus. Hier hängen die Jacken, und die Schuhe stehen im Regal.",
      { wand: "creme", boden: "plaettli", icon: "garderobe",
        passend: ["garderobe", "schuhregal", "bank", "spiegel", "briefkasten", "pflanze", "laeufer", "deckenlampe", "bild", "uhr", "kommode"],
        wuensche: ["garderobe", "schuhe", "spiegel", "sitz", "lampe", "pflanze", "teppich", "bild", "uhr"] }),
    R("wohnzimmer", "wohnhaus", "Wohnzimmer", "das Wohnzimmer", "ein Wohnzimmer",
      "Im Wohnzimmer sitzt die Familie zusammen: zum Spielen, Lesen und Plaudern.",
      { wand: "hellgelb", icon: "sofa",
        passend: ["sofa", "ecksofa", "sessel", "couchtisch", "fernseher", "sideboard", "buecherregal", "stehlampe", "teppich", "pflanze", "bild", "kamin", "uhr", "kissen", "aquarium", "radio"],
        wuensche: ["sofa", "tisch", "lampe", "teppich", "bild", "pflanze", "fernseher", "buecher", "kissen", "uhr", "fenster", "kamin"] }),
    R("kueche", "wohnhaus", "Küche", "die Küche", "eine Küche",
      "In der Küche wird gekocht. Hier gibt es einen Kochherd, einen Kühlschrank und ein Spülbecken.",
      { wand: "mint", muster: "kacheln", boden: "plaettli", icon: "kochherd",
        passend: ["kochherd", "kuehlschrank", "spuele", "kuechenschrank", "haengeschrank", "dunstabzug", "gewuerzregal", "topf", "pfanne", "mikrowelle", "kaffeemaschine", "toaster", "wasserkocher", "obstschale", "brotkorb", "tisch", "stuhl", "uhr"],
        wuensche: ["herd", "kuehlschrank", "spuele", "geschirr", "kuechenschrank", "tisch", "stuhl", "uhr", "lampe", "fruechte", "brot"] }),
    R("esszimmer", "wohnhaus", "Esszimmer", "das Esszimmer", "ein Esszimmer",
      "Im Esszimmer essen alle zusammen am grossen Tisch.",
      { wand: "pfirsich", icon: "esstisch",
        passend: ["esstisch", "stuhl", "sideboard", "kronleuchter", "deckenlampe", "teller", "geschirr", "blumenvase", "obstschale", "zopf", "kaffeetasse", "bild", "pflanze", "teppich", "uhr"],
        wuensche: ["tisch", "stuhl", "lampe", "geschirr", "essen", "blumen", "bild", "teppich", "pflanze"] }),
    R("schlafzimmer", "wohnhaus", "Schlafzimmer", "das Schlafzimmer", "ein Schlafzimmer",
      "Im Schlafzimmer schläft man. Hier stehen das Bett, der Nachttisch und der Kleiderschrank.",
      { wand: "flieder", icon: "bett",
        passend: ["bett", "doppelbett", "nachttisch", "kleiderschrank", "kommode", "tischlampe", "wecker", "teppich", "vorhangfenster", "bild", "spiegel", "pflanze", "kissen", "stehlampe", "deckenlampe"],
        wuensche: ["bett", "nachttisch", "schrank", "lampe", "teppich", "vorhang", "bild", "spiegel", "uhr", "pflanze", "kissen"] }),
    R("kinderzimmer", "wohnhaus", "Kinderzimmer", "das Kinderzimmer", "ein Kinderzimmer",
      "Das Kinderzimmer gehört den Kindern: zum Spielen, Malen und Schlafen.",
      { wand: "hellblau", muster: "sterne", boden: "teppichboden", icon: "kinderbett",
        passend: ["kinderbett", "hochbett", "spielkiste", "kloetze", "ball", "kuscheltier", "schaukelpferd", "puppenhaus", "tisch", "stuhl", "sitzsack", "regal", "poster", "teppich", "deckenlampe", "lichterkette", "girlande", "staffelei"],
        wuensche: ["bett", "spielzeug", "kuscheltier", "ball", "tisch", "stuhl", "lampe", "teppich", "bild", "regal", "malen"] }),
    R("bad", "wohnhaus", "Badezimmer", "das Badezimmer", "ein Badezimmer",
      "Im Badezimmer wäscht man sich, putzt die Zähne und badet.",
      { wand: "hellblau", muster: "kacheln", boden: "plaettli", icon: "wanne",
        passend: ["wanne", "dusche", "wc", "lavabo", "spiegel", "handtuch", "zahnputzbecher", "badteppich", "waeschekorb", "pflanze", "deckenlampe", "rundfenster"],
        wuensche: ["wanne", "wc", "lavabo", "spiegel", "handtuch", "zahnbuerste", "teppich", "lampe", "pflanze"] }),
    R("waschzimmer", "wohnhaus", "Waschzimmer", "das Waschzimmer", "ein Waschzimmer",
      "Im Waschzimmer werden die Kleider gewaschen und getrocknet.",
      { wand: "hellgrau", boden: "stein", icon: "waschmaschine",
        passend: ["waschmaschine", "tumbler", "waeschekorb", "waeschestaender", "buegelbrett", "regal", "lavabo", "deckenlampe", "handtuch", "uhr", "radio"],
        wuensche: ["waschmaschine", "tumbler", "waesche", "buegeln", "regal", "lampe", "lavabo", "uhr"] }),
    R("bastelzimmer", "wohnhaus", "Bastelzimmer", "das Bastelzimmer", "ein Bastelzimmer",
      "Im Bastelzimmer wird gemalt, geklebt und gebaut.",
      { wand: "hellgelb", muster: "punkte", boden: "dielen", icon: "staffelei",
        passend: ["staffelei", "farbtoepfe", "tisch", "stuhl", "hocker", "regal", "poster", "bild", "kloetze", "werkzeugwand", "stehlampe", "pinnwand", "teppich"],
        wuensche: ["malen", "tisch", "stuhl", "regal", "lampe", "bild", "werkzeug", "pinnwand"] }),
    R("terrasse", "wohnhaus", "Terrasse", "die Terrasse", "eine Terrasse",
      "Auf der Terrasse ist man draussen: mit Pflanzen, Liegestuhl und viel frischer Luft.",
      { wand: "hellblau", boden: "dielen", icon: "liegestuhl",
        passend: ["liegestuhl", "pflanze", "grosspflanze", "blumeneimer", "bank", "tisch", "stuhl", "lichterkette", "vogelhaus", "ball", "sandkasten", "laeufer"],
        wuensche: ["liegestuhl", "pflanze", "blumen", "tisch", "sitz", "lampe", "ball"] }),
    R("keller", "wohnhaus", "Keller", "der Keller", "einen Keller",
      "Im Keller hat es Platz für Vorräte, Velos und alles, was man gerade nicht braucht.",
      { wand: "beige", muster: "ziegel", boden: "stein", icon: "velo",
        passend: ["velo", "regal", "pakete", "werkzeugwand", "deckenlampe", "waeschekorb", "kuehlschrank", "honig", "aepfel", "milch", "hantel"],
        wuensche: ["velo", "regal", "werkzeug", "lampe", "pakete", "essen"] }),

    // --- Spital ---------------------------------------------------------------
    R("empfang", "spital", "Empfang", "der Empfang", "einen Empfang",
      "Am Empfang meldet man sich an. Hier erfährt man, wohin man gehen muss.",
      { wand: "hellblau", boden: "linoleum", icon: "empfangstheke", arbeit: true,
        passend: ["empfangstheke", "computer", "telefon", "bank", "stuhl", "pflanze", "uhr", "wasserspender", "bild", "zeitungsstaender", "erstehilfe", "rollstuhl"],
        wuensche: ["empfang", "computer", "telefon", "sitz", "uhr", "pflanze", "trinken", "zeitung", "lampe"] }),
    R("notfall", "spital", "Notfall", "der Notfall", "einen Notfall",
      "In den Notfall kommt, wer plötzlich krank ist oder sich verletzt hat. Hier wird sofort geholfen – Tag und Nacht.",
      { wand: "weiss", boden: "linoleum", icon: "spitalbett", arbeit: true,
        passend: ["spitalbett", "herzmonitor", "infusion", "rollstuhl", "paravent", "erstehilfe", "medikamente", "arztkoffer", "stethoskop", "kruecken", "liege", "uhr", "deckenlampe"],
        wuensche: ["spitalbett", "monitor", "infusion", "rollstuhl", "erstehilfe", "arztkoffer", "paravent", "uhr", "lampe"] }),
    R("paediatrie", "spital", "Kinderabteilung", "die Kinderabteilung", "eine Kinderabteilung",
      "Die Kinderabteilung heisst auch Pädiatrie. Hier arbeiten Kinderärztinnen und Kinderärzte – sie kennen sich mit Kindern besonders gut aus.",
      { wand: "hellgelb", muster: "sterne", boden: "linoleum", icon: "kuscheltier", arbeit: true,
        passend: ["spitalbett", "kinderbett", "kuscheltier", "spielkiste", "kloetze", "waage", "stethoskop", "poster", "lichterkette", "liege", "buecherstapel", "teppich", "sitzsack"],
        wuensche: ["spitalbett", "spielzeug", "kuscheltier", "waage", "arztkoffer", "bild", "buecher", "liege", "lampe"] }),
    R("radiologie", "spital", "Radiologie", "die Radiologie", "eine Radiologie",
      "In der Radiologie macht man Bilder vom Inneren des Körpers – zum Beispiel vom Knochen. So sieht man, ob etwas gebrochen ist.",
      { wand: "hellgrau", boden: "linoleum", icon: "roentgen", arbeit: true,
        passend: ["roentgen", "roentgenbild", "ultraschall", "liege", "computer", "paravent", "stuhl", "deckenlampe", "kruecken"],
        wuensche: ["roentgen", "roentgenbild", "ultraschall", "liege", "computer", "paravent", "sitz", "lampe"] }),
    R("innere", "spital", "Innere Medizin", "die Innere Medizin", "eine Innere Medizin",
      "In der Inneren Medizin kümmert man sich um Herz, Lunge und Bauch. Man hört ab, misst den Blutdruck und findet heraus, was fehlt.",
      { wand: "mint", boden: "linoleum", icon: "herzmonitor", arbeit: true,
        passend: ["spitalbett", "herzmonitor", "liege", "stethoskop", "medikamente", "computer", "schreibtisch", "stuhl", "infusion", "waage", "paravent"],
        wuensche: ["spitalbett", "monitor", "liege", "arztkoffer", "medikamente", "computer", "waage", "infusion"] }),
    R("chirurgie", "spital", "Operationssaal", "der Operationssaal", "einen Operationssaal",
      "Im Operationssaal wird operiert. Alle tragen Masken und Handschuhe, damit alles ganz sauber bleibt. Wer operiert wird, schläft tief und spürt nichts.",
      { wand: "mint", muster: "kacheln", boden: "plaettli", icon: "operationstisch", arbeit: true,
        passend: ["operationstisch", "oplampe", "herzmonitor", "infusion", "medikamente", "lavabo", "uhr", "paravent"],
        wuensche: ["operation", "oplampe", "monitor", "infusion", "lavabo", "uhr", "medikamente"] }),
    R("geburt", "spital", "Geburtsabteilung", "die Geburtsabteilung", "eine Geburtsabteilung",
      "In der Geburtsabteilung kommen Babys auf die Welt. Hebammen helfen den Müttern und den Neugeborenen.",
      { wand: "rosa", boden: "linoleum", icon: "wiege", arbeit: true,
        passend: ["spitalbett", "wiege", "brutkasten", "waage", "kuscheltier", "sessel", "blumenvase", "herzmonitor", "vorhangfenster", "deckenlampe", "teppich"],
        wuensche: ["spitalbett", "babybett", "waage", "kuscheltier", "sitz", "blumen", "vorhang", "lampe"] }),
    R("labor", "spital", "Labor", "das Labor", "ein Labor",
      "Im Labor untersucht man Blut und andere Proben – mit Maschinen und dem Mikroskop.",
      { wand: "weiss", boden: "linoleum", icon: "mikroskop", arbeit: true,
        passend: ["mikroskop", "reagenzglaeser", "zentrifuge", "tisch", "schreibtisch", "hocker", "computer", "kuehlschrank", "medikamentenschrank", "lavabo", "deckenlampe"],
        wuensche: ["mikroskop", "labor", "tisch", "computer", "kuehlschrank", "lavabo", "sitz", "lampe"] }),
    R("physio", "spital", "Physiotherapie", "die Physiotherapie", "eine Physiotherapie",
      "In der Physiotherapie übt man, sich wieder gut zu bewegen – zum Beispiel nach einem Beinbruch.",
      { wand: "hellgruen", boden: "dielen", icon: "barren", arbeit: true,
        passend: ["barren", "gymnastikball", "turnmatte", "sprossenwand", "liege", "hantel", "hometrainer", "kruecken", "spiegel", "uhr", "radio"],
        wuensche: ["physio", "ball", "matte", "klettern", "liege", "fitness", "spiegel", "musik"] }),
    R("bettenstation", "spital", "Bettenstation", "die Bettenstation", "eine Bettenstation",
      "Auf der Bettenstation schlafen die Kranken, bis sie wieder gesund sind. Pflegefachleute schauen oft nach ihnen.",
      { wand: "creme", boden: "linoleum", icon: "spitalbett", arbeit: true,
        passend: ["spitalbett", "nachttisch", "infusion", "paravent", "fernseher", "blumenvase", "tischlampe", "stuhl", "vorhangfenster", "bild", "uhr", "kissen"],
        wuensche: ["spitalbett", "nachttisch", "infusion", "paravent", "fernseher", "blumen", "lampe", "fenster", "bild"] }),
    R("apotheke", "spital", "Apotheke", "die Apotheke", "eine Apotheke",
      "In der Spitalapotheke liegen die Medikamente. Hier bekommt man, was die Ärztin oder der Arzt aufgeschrieben hat.",
      { wand: "mint", boden: "plaettli", icon: "medikamentenschrank", arbeit: true,
        passend: ["medikamentenschrank", "ladentheke", "kasse", "medikamente", "computer", "regal", "waage", "stuhl", "pflanze"],
        wuensche: ["medikamente", "theke", "kasse", "computer", "regal", "lampe"] }),
    R("augen", "spital", "Augenabteilung", "die Augenabteilung", "eine Augenabteilung",
      "In der Augenabteilung untersucht man die Augen: Wie gut siehst du? Braucht jemand eine Brille?",
      { wand: "hellblau", boden: "linoleum", icon: "sehtest", arbeit: true,
        passend: ["sehtest", "stuhl", "schreibtisch", "computer", "spiegel", "deckenlampe", "stehlampe", "liege"],
        wuensche: ["sehtest", "sitz", "computer", "spiegel", "lampe", "tisch"] }),
    R("intensiv", "spital", "Intensivstation", "die Intensivstation", "eine Intensivstation",
      "Wer sehr krank ist, wird auf der Intensivstation Tag und Nacht genau beobachtet – von Maschinen und von Menschen.",
      { wand: "hellgrau", boden: "linoleum", icon: "herzmonitor", arbeit: true,
        passend: ["spitalbett", "herzmonitor", "infusion", "ultraschall", "paravent", "medikamente", "uhr", "deckenlampe"],
        wuensche: ["spitalbett", "monitor", "infusion", "ultraschall", "paravent", "uhr"] }),
    R("spitalcafeteria", "spital", "Cafeteria", "die Cafeteria", "eine Cafeteria",
      "In der Cafeteria essen und trinken alle: der Besuch, die Kranken und die Leute, die im Spital arbeiten.",
      { wand: "pfirsich", boden: "plaettli", icon: "kaffeemaschine", arbeit: true, ausflug: true,
        passend: ["restauranttisch", "tisch", "stuhl", "kuchenvitrine", "kaffeeautomat", "ladentheke", "kasse", "kaffeetasse", "kuchen", "gipfeli", "pflanze", "menuetafel"],
        wuensche: ["tisch", "stuhl", "kaffee", "kuchen", "theke", "essen", "pflanze"] }),

    // --- Dorfzentrum ------------------------------------------------------------
    R("eingangshalle", "zentrum", "Eingangshalle", "die Eingangshalle", "eine Eingangshalle",
      "In der Eingangshalle kommt man an. Hier gibt es Bänke, einen Plan und Platz für alle.",
      { wand: "creme", boden: "stein", icon: "bank",
        passend: ["bank", "grosspflanze", "pflanze", "uhr", "weltkarte", "briefkasten", "wasserspender", "laeufer", "kronleuchter", "bild", "pinnwand"],
        wuensche: ["sitz", "pflanze", "uhr", "lampe", "bild", "pinnwand", "trinken"] }),
    R("lebensmittel", "zentrum", "Lebensmittelladen", "der Lebensmittelladen", "einen Lebensmittelladen",
      "Im Lebensmittelladen kauft man Brot, Milch, Früchte und Gemüse.",
      { wand: "hellgruen", boden: "plaettli", icon: "obstkiste", arbeit: true, ausflug: true,
        passend: ["ladentheke", "kasse", "warenregal", "obstkiste", "gemuesekiste", "kuehltheke", "einkaufswagen", "brotregal", "milch", "kaese", "aepfel"],
        wuensche: ["theke", "kasse", "waren", "fruechte", "gemuese", "kuehlschrank", "einkaufswagen", "brot"] }),
    R("baeckerei", "zentrum", "Bäckerei", "die Bäckerei", "eine Bäckerei",
      "In der Bäckerei duftet es nach frischem Brot, Gipfeli und Zopf.",
      { wand: "pfirsich", boden: "dielen", icon: "brotregal", arbeit: true, ausflug: true,
        passend: ["brotregal", "ladentheke", "kasse", "kuchenvitrine", "gipfeli", "zopf", "kuchen", "brotkorb", "tisch", "stuhl", "kaffeemaschine"],
        wuensche: ["brot", "theke", "kasse", "kuchen", "tisch", "kaffee"] }),
    R("spielwaren", "zentrum", "Spielwarenladen", "der Spielwarenladen", "einen Spielwarenladen",
      "Im Spielwarenladen gibt es Puppen, Bälle, Bauklötze und Spiele.",
      { wand: "hellblau", muster: "punkte", icon: "schaukelpferd", arbeit: true, ausflug: true,
        passend: ["ladentheke", "kasse", "regal", "spielkiste", "kloetze", "ball", "kuscheltier", "schaukelpferd", "puppenhaus", "trommel", "poster"],
        wuensche: ["theke", "kasse", "regal", "spielzeug", "ball", "kuscheltier", "trommel"] }),
    R("kleider", "zentrum", "Kleiderladen", "der Kleiderladen", "einen Kleiderladen",
      "Im Kleiderladen probiert man Hosen, Jacken und Schuhe an.",
      { wand: "rosa", icon: "kleiderstaender", arbeit: true, ausflug: true,
        passend: ["kleiderstaender", "schaufensterpuppe", "spiegel", "ladentheke", "kasse", "schuhregal", "hocker", "paravent", "regal"],
        wuensche: ["kleider", "spiegel", "theke", "kasse", "schuhe", "sitz"] }),
    R("blumen", "zentrum", "Blumenladen", "der Blumenladen", "einen Blumenladen",
      "Im Blumenladen gibt es Blumen und Pflanzen – für den Garten oder als Geschenk.",
      { wand: "mint", boden: "stein", icon: "blumeneimer", arbeit: true, ausflug: true,
        passend: ["blumeneimer", "blumenvase", "blumenstrauss", "pflanze", "grosspflanze", "kaktus", "bambus", "haengepflanze", "ladentheke", "kasse", "regal"],
        wuensche: ["blumen", "pflanze", "theke", "kasse", "regal", "lampe"] }),
    R("coiffeur", "zentrum", "Coiffeur", "der Coiffeur", "einen Coiffeur",
      "Beim Coiffeur werden die Haare gewaschen, geschnitten und frisiert.",
      { wand: "flieder", boden: "plaettli", icon: "coiffeurstuhl", arbeit: true, ausflug: true,
        passend: ["coiffeurstuhl", "coiffeurspiegel", "trockenhaube", "lavabo", "handtuch", "ladentheke", "kasse", "zeitungsstaender", "bank", "pflanze"],
        wuensche: ["coiffeur", "spiegel", "lavabo", "handtuch", "kasse", "zeitung", "sitz"] }),
    R("bibliothek", "zentrum", "Bibliothek", "die Bibliothek", "eine Bibliothek",
      "In der Bibliothek kann man Bücher ausleihen und in Ruhe lesen. Danach bringt man sie zurück.",
      { wand: "creme", muster: "holz", icon: "buecherregal", arbeit: true, ausflug: true,
        passend: ["buecherregal", "buecherwagen", "lesekissen", "sessel", "tisch", "stuhl", "stehlampe", "globus", "weltkarte", "buecherstapel", "computer", "teppich", "zeitungsstaender"],
        wuensche: ["buecher", "lesen", "sitz", "tisch", "lampe", "globus", "karte", "teppich", "computer"] }),
    R("restaurant", "zentrum", "Restaurant", "das Restaurant", "ein Restaurant",
      "Im Restaurant bestellt man etwas zu essen. In der Küche wird gekocht, und das Essen kommt an den Tisch.",
      { wand: "pfirsich", muster: "streifen", icon: "restauranttisch", arbeit: true, ausflug: true,
        passend: ["restauranttisch", "stuhl", "barhocker", "pizzaofen", "menuetafel", "teller", "pizza", "kaffeetasse", "blumenvase", "kochherd", "ladentheke", "kronleuchter", "pflanze"],
        wuensche: ["restaurant", "stuhl", "ofen", "menue", "essen", "blumen", "lampe", "herd"] }),
    R("cafe", "zentrum", "Café", "das Café", "ein Café",
      "Im Café gibt es Kuchen, Glace und etwas Feines zu trinken.",
      { wand: "rosa", muster: "streifen", boden: "dielen", icon: "kuchenvitrine", arbeit: true, ausflug: true,
        passend: ["kuchenvitrine", "glacetheke", "restauranttisch", "stuhl", "kaffeemaschine", "kaffeetasse", "kuchen", "glace", "gipfeli", "menuetafel", "blumenvase", "lichterkette"],
        wuensche: ["kuchen", "glace", "tisch", "stuhl", "kaffee", "menue", "blumen"] }),
    R("spielplatz", "zentrum", "Spielplatz", "der Spielplatz", "einen Spielplatz",
      "Auf dem Spielplatz wird gerutscht, geschaukelt, geklettert und im Sand gebuddelt.",
      { wand: "hellblau", boden: "rasen", icon: "rutsche", ausflug: true,
        passend: ["rutsche", "schaukel", "sandkasten", "trampolin", "klettergeruest", "ball", "bank", "grosspflanze", "liegestuhl", "vogelhaus"],
        wuensche: ["rutsche", "schaukel", "sand", "klettern", "trampolin", "ball", "sitz", "pflanze"] }),
    R("hallenbad", "zentrum", "Hallenbad", "das Hallenbad", "ein Hallenbad",
      "Im Hallenbad kann man schwimmen, auch wenn es draussen kalt ist.",
      { wand: "hellblau", muster: "kacheln", boden: "plaettli", icon: "schwimmbecken", arbeit: true, ausflug: true,
        passend: ["schwimmbecken", "sprungbrett", "rettungsring", "liegestuhl", "ball", "dusche", "handtuch", "bank", "grosspflanze", "uhr"],
        wuensche: ["becken", "sprungbrett", "rettungsring", "liegestuhl", "dusche", "handtuch", "ball"] }),
    R("turnhalle", "zentrum", "Turnhalle", "die Turnhalle", "eine Turnhalle",
      "In der Turnhalle rennt, springt und klettert man. Hier gibt es Matten, Bälle und Sprossenwände.",
      { wand: "pfirsich", boden: "dielen", icon: "sprossenwand", arbeit: true, ausflug: true,
        passend: ["sprossenwand", "kletterwand", "turnmatte", "basketballkorb", "ball", "gymnastikball", "trampolin", "bank", "hantel", "uhr"],
        wuensche: ["klettern", "matte", "basketball", "ball", "sitz", "trampolin", "uhr"] }),
    R("kino", "zentrum", "Kino", "das Kino", "ein Kino",
      "Im Kino schaut man Filme auf einer riesigen Leinwand – mit Popcorn!",
      { wand: "dunkelblau", boden: "teppichboden", icon: "leinwand", arbeit: true, ausflug: true,
        passend: ["leinwand", "kinosessel", "popcorn", "glacetheke", "ladentheke", "kasse", "deckenlampe", "poster", "lichterkette"],
        wuensche: ["kino", "kinosessel", "popcorn", "glace", "bild", "kasse"] }),
    R("schule", "zentrum", "Schulzimmer", "das Schulzimmer", "ein Schulzimmer",
      "Im Schulzimmer lernen die Kinder lesen, schreiben und rechnen.",
      { wand: "hellgelb", boden: "linoleum", icon: "wandtafel", arbeit: true,
        passend: ["wandtafel", "schulpult", "stuhl", "globus", "weltkarte", "buecherregal", "uhr", "pflanze", "computer", "pinnwand", "staffelei"],
        wuensche: ["tafel", "pult", "stuhl", "globus", "karte", "buecher", "uhr", "pflanze"] }),
    R("kita", "zentrum", "Kita", "die Kita", "eine Kita",
      "In der Kita spielen kleine Kinder zusammen, während ihre Eltern arbeiten.",
      { wand: "rosa", muster: "herzen", boden: "teppichboden", icon: "spielkiste", arbeit: true,
        passend: ["spielkiste", "kloetze", "ball", "kuscheltier", "schaukelpferd", "puppenhaus", "kinderbett", "rutsche", "tisch", "stuhl", "sitzsack", "teppich", "poster", "girlande"],
        wuensche: ["spielzeug", "kuscheltier", "bett", "ball", "tisch", "stuhl", "teppich", "bild", "rutsche"] }),
    R("post", "zentrum", "Post", "die Post", "eine Post",
      "Auf der Post gibt man Briefe und Pakete auf. Die Pöstlerin oder der Pöstler bringt sie dann nach Hause.",
      { wand: "hellgelb", boden: "plaettli", icon: "briefkasten", arbeit: true, ausflug: true,
        passend: ["briefkasten", "pakete", "ladentheke", "kasse", "waage", "regal", "computer", "stuhl", "uhr"],
        wuensche: ["post", "pakete", "theke", "kasse", "waage", "regal", "uhr"] }),
    R("musik", "zentrum", "Musikzimmer", "das Musikzimmer", "ein Musikzimmer",
      "Im Musikzimmer wird gesungen und musiziert – mit Klavier, Trommel und Gitarre.",
      { wand: "flieder", muster: "wellen", icon: "klavier", arbeit: true, ausflug: true,
        passend: ["klavier", "trommel", "gitarre", "radio", "hocker", "stuhl", "poster", "teppich", "stehlampe", "buecherregal"],
        wuensche: ["klavier", "trommel", "gitarre", "sitz", "teppich", "lampe", "bild"] }),
    R("toiletten", "zentrum", "Toiletten", "die Toiletten", "Toiletten",
      "Toiletten braucht jedes Haus, in dem viele Leute sind – mit einem Lavabo zum Händewaschen.",
      { wand: "hellblau", muster: "kacheln", boden: "plaettli", icon: "wc",
        passend: ["wc", "lavabo", "spiegel", "handtuch", "pflanze", "deckenlampe"],
        wuensche: ["wc", "lavabo", "spiegel", "handtuch", "pflanze", "lampe"] }),
    R("velowerkstatt", "zentrum", "Velowerkstatt", "die Velowerkstatt", "eine Velowerkstatt",
      "In der Velowerkstatt werden Velos geflickt: Pneus pumpen, Ketten ölen, Bremsen einstellen.",
      { wand: "hellgrau", muster: "ziegel", boden: "stein", icon: "velo", arbeit: true,
        passend: ["velo", "werkzeugwand", "regal", "ladentheke", "kasse", "hocker", "pakete", "deckenlampe"],
        wuensche: ["velo", "werkzeug", "regal", "kasse", "theke", "lampe"] }),

    // --- Bürohaus ---------------------------------------------------------------
    R("bueroempfang", "buero", "Empfang", "der Empfang", "einen Empfang",
      "Am Empfang begrüsst man die Gäste und zeigt ihnen den Weg.",
      { wand: "creme", boden: "stein", icon: "empfangstheke", arbeit: true,
        passend: ["empfangstheke", "computer", "telefon", "sessel", "sofa", "couchtisch", "grosspflanze", "uhr", "wasserspender", "bild", "kronleuchter"],
        wuensche: ["empfang", "computer", "telefon", "sitz", "pflanze", "uhr", "trinken"] }),
    R("grossraum", "buero", "Grossraumbüro", "das Grossraumbüro", "ein Grossraumbüro",
      "Im Grossraumbüro arbeiten viele zusammen an Schreibtischen und Computern.",
      { wand: "hellgrau", boden: "teppichboden", icon: "computer", arbeit: true,
        passend: ["schreibtisch", "buerostuhl", "computer", "laptop", "telefon", "aktenschrank", "pinnwand", "drucker", "grosspflanze", "tischlampe", "uhr", "whiteboard"],
        wuensche: ["schreibtisch", "buerostuhl", "computer", "telefon", "akten", "pinnwand", "pflanze", "lampe"] }),
    R("einzelbuero", "buero", "Einzelbüro", "das Einzelbüro", "ein Einzelbüro",
      "Ein Büro für eine Person: Hier ist es ruhig zum Nachdenken und Telefonieren.",
      { wand: "mint", icon: "buerostuhl", arbeit: true,
        passend: ["schreibtisch", "buerostuhl", "computer", "laptop", "telefon", "sessel", "buecherregal", "pflanze", "bild", "tischlampe", "teppich", "kaffeemaschine"],
        wuensche: ["schreibtisch", "buerostuhl", "computer", "telefon", "buecher", "bild", "pflanze", "lampe", "teppich"] }),
    R("sitzung", "buero", "Sitzungszimmer", "das Sitzungszimmer", "ein Sitzungszimmer",
      "Im Sitzungszimmer trifft man sich und bespricht, was zu tun ist.",
      { wand: "hellblau", boden: "teppichboden", icon: "sitzungstisch", arbeit: true,
        passend: ["sitzungstisch", "buerostuhl", "whiteboard", "leinwand", "laptop", "wasserspender", "kaffeetasse", "pflanze", "uhr"],
        wuensche: ["tisch", "buerostuhl", "tafel", "computer", "trinken", "uhr", "pflanze"] }),
    R("drucker", "buero", "Druckerraum", "der Druckerraum", "einen Druckerraum",
      "Im Druckerraum stehen Drucker und Kopierer. Hier kommt das Papier heraus.",
      { wand: "hellgrau", boden: "linoleum", icon: "kopierer", arbeit: true,
        passend: ["kopierer", "drucker", "tisch", "regal", "aktenschrank", "ordnerregal", "pakete", "deckenlampe"],
        wuensche: ["kopierer", "drucker", "tisch", "regal", "akten", "lampe"] }),
    R("buerowc", "buero", "WC", "das WC", "ein WC",
      "Auch im Büro braucht man ein WC – und ein Lavabo zum Händewaschen.",
      { wand: "hellblau", muster: "kacheln", boden: "plaettli", icon: "wc",
        passend: ["wc", "lavabo", "spiegel", "handtuch", "pflanze", "deckenlampe"],
        wuensche: ["wc", "lavabo", "spiegel", "handtuch", "lampe", "pflanze"] }),
    R("cafeteria", "buero", "Cafeteria", "die Cafeteria", "eine Cafeteria",
      "In der Cafeteria macht man Pause – mit Kaffee, Tee und einem Znüni.",
      { wand: "pfirsich", boden: "plaettli", icon: "kaffeeautomat", arbeit: true,
        passend: ["kaffeeautomat", "tisch", "stuhl", "kuehlschrank", "spuele", "mikrowelle", "wasserkocher", "kaffeetasse", "obstschale", "gipfeli", "sofa", "pflanze", "toeggelikasten"],
        wuensche: ["kaffee", "tisch", "stuhl", "kuehlschrank", "fruechte", "sofa", "spiel"] }),
    R("archiv", "buero", "Archiv", "das Archiv", "ein Archiv",
      "Im Archiv werden wichtige Papiere in Ordnern und Kisten aufbewahrt.",
      { wand: "beige", boden: "linoleum", icon: "ordnerregal", arbeit: true,
        passend: ["ordnerregal", "aktenschrank", "pakete", "regal", "tisch", "stuhl", "deckenlampe", "uhr"],
        wuensche: ["akten", "regal", "pakete", "tisch", "lampe", "uhr"] }),
    R("computerraum", "buero", "Computerraum", "der Computerraum", "einen Computerraum",
      "Im Computerraum stehen grosse Computer, die Tag und Nacht arbeiten. Man nennt sie Server.",
      { wand: "dunkelblau", boden: "linoleum", icon: "serverschrank", arbeit: true,
        passend: ["serverschrank", "computer", "schreibtisch", "buerostuhl", "laptop", "telefon", "kopierer", "deckenlampe", "uhr"],
        wuensche: ["server", "computer", "schreibtisch", "buerostuhl", "telefon", "lampe", "uhr"] }),
    R("atelier", "buero", "Atelier", "das Atelier", "ein Atelier",
      "Im Atelier wird gezeichnet, entworfen und gebastelt – zum Beispiel neue Spielsachen.",
      { wand: "weiss", boden: "dielen", icon: "staffelei", arbeit: true,
        passend: ["staffelei", "farbtoepfe", "tisch", "hocker", "regal", "pinnwand", "poster", "kloetze", "computer", "stehlampe", "werkzeugwand"],
        wuensche: ["malen", "tisch", "sitz", "regal", "pinnwand", "lampe", "bild"] }),
    R("fitness", "buero", "Fitnessraum", "der Fitnessraum", "einen Fitnessraum",
      "Im Fitnessraum bewegen sich alle in der Pause – auf dem Laufband, mit Hanteln und auf der Matte.",
      { wand: "hellgruen", boden: "linoleum", icon: "laufband", arbeit: true,
        passend: ["laufband", "hometrainer", "hantel", "turnmatte", "gymnastikball", "sprossenwand", "spiegel", "wasserspender", "radio", "uhr"],
        wuensche: ["fitness", "matte", "ball", "spiegel", "trinken", "musik"] }),
  ];
  const RAEUME = Object.fromEntries(RAEUME_LISTE.map((raum) => [raum.id, raum]));
  HAEUSER.forEach((haus) => { haus.raeume = RAEUME_LISTE.filter((raum) => raum.haus === haus.id).map((raum) => raum.id); });

  // ---------------------------------------------------------------------------
  // Wünsche für das eigene Zimmer (gelb)
  // ---------------------------------------------------------------------------
  // tag → wie der Wunsch heisst und welches Ding "Zeig mir" vorschlägt.
  const DING_WUENSCHE = {
    bett: { ein: "ein Bett", zeige: "bett" },
    schrank: { ein: "einen Schrank", zeige: "kleiderschrank" },
    nachttisch: { ein: "einen Nachttisch", zeige: "nachttisch" },
    lampe: { ein: "eine Lampe", zeige: "stehlampe" },
    teppich: { ein: "einen Teppich", zeige: "teppich" },
    bild: { ein: "ein Bild an der Wand", zeige: "bild" },
    pflanze: { ein: "eine Pflanze", zeige: "pflanze" },
    blumen: { ein: "Blumen", zeige: "blumenvase" },
    tisch: { ein: "einen Tisch", zeige: "tisch" },
    stuhl: { ein: "einen Stuhl", zeige: "stuhl" },
    sitz: { ein: "etwas zum Sitzen", zeige: "sessel" },
    sofa: { ein: "ein Sofa", zeige: "sofa" },
    kissen: { ein: "ein Kissen", zeige: "kissen" },
    fenster: { ein: "ein Fenster", zeige: "fenster" },
    vorhang: { ein: "einen Vorhang", zeige: "vorhangfenster" },
    spielzeug: { ein: "Spielsachen", zeige: "spielkiste" },
    kuscheltier: { ein: "ein Kuscheltier", zeige: "kuscheltier" },
    ball: { ein: "einen Ball", zeige: "ball" },
    buecher: { ein: "Bücher", zeige: "buecherregal" },
    lesen: { ein: "ein Lesekissen", zeige: "lesekissen" },
    uhr: { ein: "eine Uhr", zeige: "uhr" },
    spiegel: { ein: "einen Spiegel", zeige: "spiegel" },
    regal: { ein: "ein Regal", zeige: "regal" },
    fernseher: { ein: "einen Fernseher", zeige: "fernseher" },
    kamin: { ein: "ein Cheminée", zeige: "kamin" },
    garderobe: { ein: "eine Garderobe", zeige: "garderobe" },
    schuhe: { ein: "ein Schuhregal", zeige: "schuhregal" },
    malen: { ein: "Farben zum Malen", zeige: "farbtoepfe" },
    werkzeug: { ein: "Werkzeug", zeige: "werkzeugwand" },
    pinnwand: { ein: "eine Pinnwand", zeige: "pinnwand" },
    velo: { ein: "ein Velo", zeige: "velo" },
    pakete: { ein: "Pakete", zeige: "pakete" },
    liegestuhl: { ein: "einen Liegestuhl", zeige: "liegestuhl" },
    // Küche und Bad
    herd: { ein: "einen Kochherd", zeige: "kochherd" },
    kuehlschrank: { ein: "einen Kühlschrank", zeige: "kuehlschrank" },
    spuele: { ein: "ein Spülbecken", zeige: "spuele" },
    geschirr: { ein: "Geschirr", zeige: "geschirr" },
    kuechenschrank: { ein: "einen Küchenschrank", zeige: "kuechenschrank" },
    fruechte: { ein: "Früchte", zeige: "obstschale" },
    brot: { ein: "Brot", zeige: "brotkorb" },
    essen: { ein: "etwas zu essen", zeige: "teller" },
    kaffee: { ein: "eine Kaffeemaschine", zeige: "kaffeemaschine" },
    trinken: { ein: "Wasser zum Trinken", zeige: "wasserspender" },
    wanne: { ein: "eine Badewanne oder eine Dusche", zeige: "wanne" },
    dusche: { ein: "eine Dusche", zeige: "dusche" },
    wc: { ein: "ein WC", zeige: "wc" },
    lavabo: { ein: "ein Lavabo", zeige: "lavabo" },
    handtuch: { ein: "Tücher zum Abtrocknen", zeige: "handtuch" },
    zahnbuerste: { ein: "Zahnbürsten", zeige: "zahnputzbecher" },
    waschmaschine: { ein: "eine Waschmaschine", zeige: "waschmaschine" },
    tumbler: { ein: "einen Tumbler", zeige: "tumbler" },
    waesche: { ein: "einen Wäschekorb", zeige: "waeschekorb" },
    buegeln: { ein: "ein Bügelbrett", zeige: "buegelbrett" },
    // Spital
    spitalbett: { ein: "ein Spitalbett", zeige: "spitalbett" },
    monitor: { ein: "einen Herzmonitor", zeige: "herzmonitor" },
    infusion: { ein: "einen Infusionsständer", zeige: "infusion" },
    rollstuhl: { ein: "einen Rollstuhl", zeige: "rollstuhl" },
    erstehilfe: { ein: "einen Erste-Hilfe-Kasten", zeige: "erstehilfe" },
    arztkoffer: { ein: "einen Arztkoffer", zeige: "arztkoffer" },
    paravent: { ein: "einen Paravent", zeige: "paravent" },
    waage: { ein: "eine Waage", zeige: "waage" },
    liege: { ein: "eine Liege", zeige: "liege" },
    roentgen: { ein: "ein Röntgengerät", zeige: "roentgen" },
    roentgenbild: { ein: "ein Röntgenbild an der Wand", zeige: "roentgenbild" },
    ultraschall: { ein: "ein Ultraschallgerät", zeige: "ultraschall" },
    medikamente: { ein: "Medikamente", zeige: "medikamentenschrank" },
    operation: { ein: "einen Operationstisch", zeige: "operationstisch" },
    oplampe: { ein: "eine Operationslampe", zeige: "oplampe" },
    babybett: { ein: "ein Babybettchen", zeige: "wiege" },
    mikroskop: { ein: "ein Mikroskop", zeige: "mikroskop" },
    labor: { ein: "Reagenzgläser", zeige: "reagenzglaeser" },
    physio: { ein: "einen Gehbarren", zeige: "barren" },
    sehtest: { ein: "eine Sehtest-Tafel", zeige: "sehtest" },
    empfang: { ein: "eine Empfangstheke", zeige: "empfangstheke" },
    computer: { ein: "einen Computer", zeige: "computer" },
    telefon: { ein: "ein Telefon", zeige: "telefon" },
    zeitung: { ein: "Zeitungen", zeige: "zeitungsstaender" },
    // Läden, Restaurant, Freizeit
    theke: { ein: "eine Theke", zeige: "ladentheke" },
    kasse: { ein: "eine Kasse", zeige: "kasse" },
    waren: { ein: "ein Warenregal", zeige: "warenregal" },
    gemuese: { ein: "Gemüse", zeige: "gemuesekiste" },
    einkaufswagen: { ein: "einen Einkaufswagen", zeige: "einkaufswagen" },
    kuchen: { ein: "Kuchen", zeige: "kuchenvitrine" },
    glace: { ein: "Glace", zeige: "glacetheke" },
    kleider: { ein: "Kleider", zeige: "kleiderstaender" },
    coiffeur: { ein: "einen Coiffeurstuhl", zeige: "coiffeurstuhl" },
    restaurant: { ein: "einen Restauranttisch", zeige: "restauranttisch" },
    ofen: { ein: "einen Pizzaofen", zeige: "pizzaofen" },
    menue: { ein: "eine Menütafel", zeige: "menuetafel" },
    post: { ein: "einen Briefkasten", zeige: "briefkasten" },
    globus: { ein: "einen Globus", zeige: "globus" },
    karte: { ein: "eine Weltkarte", zeige: "weltkarte" },
    tafel: { ein: "eine Wandtafel", zeige: "wandtafel" },
    pult: { ein: "ein Schulpult", zeige: "schulpult" },
    rutsche: { ein: "eine Rutschbahn", zeige: "rutsche" },
    schaukel: { ein: "eine Schaukel", zeige: "schaukel" },
    sand: { ein: "einen Sandkasten", zeige: "sandkasten" },
    klettern: { ein: "etwas zum Klettern", zeige: "kletterwand" },
    trampolin: { ein: "ein Trampolin", zeige: "trampolin" },
    becken: { ein: "ein Schwimmbecken", zeige: "schwimmbecken" },
    sprungbrett: { ein: "ein Sprungbrett", zeige: "sprungbrett" },
    rettungsring: { ein: "einen Rettungsring", zeige: "rettungsring" },
    matte: { ein: "eine Turnmatte", zeige: "turnmatte" },
    basketball: { ein: "einen Basketballkorb", zeige: "basketballkorb" },
    fitness: { ein: "ein Fitnessgerät", zeige: "laufband" },
    kino: { ein: "eine Kinoleinwand", zeige: "leinwand" },
    kinosessel: { ein: "Kinosessel", zeige: "kinosessel" },
    popcorn: { ein: "Popcorn", zeige: "popcorn" },
    klavier: { ein: "ein Klavier", zeige: "klavier" },
    trommel: { ein: "eine Trommel", zeige: "trommel" },
    gitarre: { ein: "eine Gitarre", zeige: "gitarre" },
    musik: { ein: "Musik", zeige: "radio" },
    spiel: { ein: "einen Töggelikasten", zeige: "toeggelikasten" },
    // Büro
    schreibtisch: { ein: "einen Schreibtisch", zeige: "schreibtisch" },
    buerostuhl: { ein: "einen Bürostuhl", zeige: "buerostuhl" },
    akten: { ein: "Ordner für die Akten", zeige: "ordnerregal" },
    drucker: { ein: "einen Drucker", zeige: "drucker" },
    kopierer: { ein: "einen Kopierer", zeige: "kopierer" },
    server: { ein: "einen Server", zeige: "serverschrank" },
    // Lieblingssachen der Tiere
    bambus: { ein: "Bambus", zeige: "bambus" },
    rueebli: { ein: "Rüebli", zeige: "rueebli" },
    honig: { ein: "Honig", zeige: "honig" },
    nuesse: { ein: "Nüsse", zeige: "nuesse" },
    kaese: { ein: "Käse", zeige: "kaese" },
    fisch: { ein: "einen Fisch", zeige: "fisch" },
    melone: { ein: "eine Melone", zeige: "melone" },
    beeren: { ein: "Beeren", zeige: "beeren" },
    knochen: { ein: "einen Knochen", zeige: "knochen" },
    aquarium: { ein: "ein Aquarium", zeige: "aquarium" },
    kratzbaum: { ein: "einen Kratzbaum", zeige: "kratzbaum" },
    laub: { ein: "einen Laubhaufen", zeige: "laubhaufen" },
    heu: { ein: "Heu", zeige: "heuballen" },
    koerbchen: { ein: "ein Körbchen", zeige: "hundekorb" },
    milch: { ein: "Milch", zeige: "milch" },
    aepfel: { ein: "Äpfel", zeige: "aepfel" },
  };

  // ---------------------------------------------------------------------------
  // Wünsche für das Haus (grün) und für die anderen Häuser (blau)
  // ---------------------------------------------------------------------------
  // Grün: welche Zimmer ein Haus haben sollte – die vorderen sind wichtiger
  // und werden öfter gewünscht.
  const HAUS_WUENSCHE = {
    wohnhaus: ["bad", "kueche", "wohnzimmer", "waschzimmer", "eingang", "esszimmer", "kinderzimmer", "schlafzimmer", "terrasse"],
    spital: ["empfang", "notfall", "radiologie", "labor", "apotheke", "bettenstation", "spitalcafeteria"],
    zentrum: ["eingangshalle", "toiletten", "restaurant", "lebensmittel", "cafe", "spielplatz", "bibliothek"],
    buero: ["bueroempfang", "buerowc", "cafeteria", "drucker", "sitzung", "archiv"],
  };

  // Blau: was ein Tier in einem anderen Haus braucht. warum ist der Satz
  // dahinter – er macht aus dem Wunsch eine kleine Geschichte.
  const FREMD_WUENSCHE = {
    wohnhaus: [
      { haus: "zentrum", raum: "spielplatz", warum: "Dort spiele ich am Nachmittag." },
      { haus: "zentrum", raum: "lebensmittel", warum: "Dort kaufe ich mein Essen ein." },
      { haus: "zentrum", raum: "bibliothek", warum: "Dort hole ich mir Bücher." },
      { haus: "zentrum", raum: "baeckerei", warum: "Dort hole ich frisches Brot." },
      { haus: "zentrum", raum: "hallenbad", warum: "Ich gehe so gern schwimmen." },
      { haus: "zentrum", raum: "schule", warum: "Dort lerne ich lesen und rechnen." },
      { haus: "spital", raum: "notfall", warum: "Falls ich mich einmal verletze." },
      { haus: "spital", raum: "paediatrie", warum: "Dort hilft man kranken Kindern." },
      { haus: "buero", raum: "grossraum", warum: "Dort möchte ich arbeiten." },
      { haus: "buero", raum: "einzelbuero", warum: "Dort möchte ich arbeiten." },
    ],
    spital: [
      { haus: "wohnhaus", raum: "schlafzimmer", warum: "Nach der Arbeit muss ich gut schlafen." },
      { haus: "wohnhaus", raum: "kueche", warum: "Nach der Arbeit koche ich gern." },
      { haus: "zentrum", raum: "restaurant", warum: "In der Pause esse ich gern auswärts." },
      { haus: "zentrum", raum: "blumen", warum: "Blumen freuen die Kranken." },
      { haus: "zentrum", raum: "cafe", warum: "Nach der Arbeit gönne ich mir ein Stück Kuchen." },
      { haus: "buero", raum: "grossraum", warum: "Dort wird für das Spital geplant." },
    ],
    zentrum: [
      { haus: "wohnhaus", raum: "schlafzimmer", warum: "Dort wohne ich nach der Arbeit." },
      { haus: "wohnhaus", raum: "kueche", warum: "Dort koche ich am Abend." },
      { haus: "wohnhaus", raum: "wohnzimmer", warum: "Dort ruhe ich mich am Abend aus." },
      { haus: "spital", raum: "notfall", warum: "Falls sich jemand verletzt." },
      { haus: "buero", raum: "grossraum", warum: "Von dort kommen viele Gäste." },
      { haus: "buero", raum: "cafeteria", warum: "Dort trinke ich mit Freunden Kaffee." },
    ],
    buero: [
      { haus: "wohnhaus", raum: "schlafzimmer", warum: "Nach der Arbeit gehe ich nach Hause." },
      { haus: "zentrum", raum: "restaurant", warum: "Dort esse ich am Mittag." },
      { haus: "zentrum", raum: "cafe", warum: "Dort hole ich mir einen Kuchen." },
      { haus: "zentrum", raum: "turnhalle", warum: "Dort turne ich nach der Arbeit." },
      { haus: "zentrum", raum: "post", warum: "Dort schicke ich die Briefe ab." },
      { haus: "zentrum", raum: "kita", warum: "Dort spielen meine Kinder, wenn ich arbeite." },
      { haus: "spital", raum: "notfall", warum: "Falls sich jemand verletzt." },
    ],
  };

  // ---------------------------------------------------------------------------
  // Die Tiere
  // ---------------------------------------------------------------------------
  // Die zwölf der App (train-art.js, DRIVERS) und vier neue. Farben und Ohren
  // wie die Chauffeure der Lok; was sie erzählen, stammt aus den Steckbriefen
  // der Leseecke (lesen-detektive.js), in der Ich-Form.
  //   namen   aus denen ein Name gezogen wird (Leo, Pino, Mia, Tim und Fred
  //           kennen die Kinder aus den Büchern)
  //   mag     ein Lieblingsding (tag) und eine Lieblingsfarbe (Familie)
  const TIERE = {
    fox: { name: "Fuchs", der: "der Fuchs", coat: "#e8763a", inner: "#ffd9b8", ear: "point", namen: ["Fino", "Flora", "Felix", "Fanny"],
      mag: { ding: "beeren", farbe: "orange" },
      isst: "Beeren, Käfer und Würmer – ich bin nicht wählerisch.",
      fakt: "Ich höre eine Maus sogar unter dem Schnee. Dann springe ich hoch und tauche mit der Nase voran hinein." },
    bear: { name: "Bär", der: "der Bär", coat: "#9a6b46", inner: "#d8b48f", ear: "round", namen: ["Bruno", "Berta", "Benno", "Bella"],
      mag: { ding: "honig", farbe: "gelb" },
      isst: "Honig! Und Beeren und Fisch.",
      fakt: "Im Winter halte ich in meiner Höhle eine lange Winterruhe." },
    rabbit: { name: "Hase", der: "der Hase", coat: "#f0ece6", inner: "#f7b8c4", ear: "long", namen: ["Hoppel", "Lilli", "Hannes", "Hanna"],
      mag: { ding: "rueebli", farbe: "rosa" },
      isst: "Rüebli, Gras und Kräuter. Im Winter knabbere ich auch Rinde.",
      fakt: "Ich wohne auf Feldern und Wiesen. Ich grabe keinen Bau – ich ruhe in einer kleinen Mulde, der Sasse." },
    cat: { name: "Katze", der: "die Katze", coat: "#8d8f9c", inner: "#e6e2ee", ear: "point", namen: ["Tim", "Mimi", "Minka", "Kasimir"],
      mag: { ding: "kratzbaum", farbe: "violett" },
      isst: "Fisch! Mmh, Fisch.",
      fakt: "Im Dunkeln sehe ich viel besser als du. Und ich schlafe gern – bis zu 15 Stunden am Tag." },
    panda: { name: "Panda", der: "der Panda", coat: "#f4f1ec", inner: "#2f3138", ear: "round", namen: ["Pandi", "Ping", "Mei", "Bao"],
      mag: { ding: "bambus", farbe: "gruen" },
      isst: "Bambus! Ich kaue bis zu 14 Stunden am Tag Bambus.",
      fakt: "Ich wohne in den Bambuswäldern in China. An den Vorderpfoten habe ich einen Extra-Knochen – damit halte ich den Bambus wie mit einem Daumen." },
    frog: { name: "Frosch", der: "der Frosch", coat: "#5cb85c", inner: "#c9ea9a", ear: "eyes", namen: ["Fred", "Frida", "Quaki", "Franz"],
      mag: { ding: "aquarium", farbe: "gruen" },
      isst: "Fliegen und Mücken – die fange ich mit meiner langen Zunge.",
      fakt: "Ich habe mein Leben als Kaulquappe im Wasser begonnen. Und ich trinke durch meine Haut!" },
    owl: { name: "Eule", der: "die Eule", coat: "#a9814f", inner: "#f3e2c0", ear: "tuft", namen: ["Ella", "Olli", "Uli", "Eulalia"],
      mag: { ding: "buecher", farbe: "blau" },
      isst: "Käfer und anderes Krabbelzeug.",
      fakt: "Ich jage in der Nacht und fliege fast ohne ein Geräusch." },
    penguin: { name: "Pinguin", der: "der Pinguin", coat: "#3a4250", inner: "#ffffff", ear: "none", namen: ["Pino", "Pia", "Paul", "Pinga"],
      mag: { ding: "fisch", farbe: "blau" },
      isst: "Fische, Krill und Tintenfische – mmh!",
      fakt: "Ich komme aus der Antarktis, rund um den Südpol. Bei uns wärmt der Papa das Ei auf seinen Füssen." },
    lion: { name: "Löwe", der: "der Löwe", coat: "#e0a53c", inner: "#f6dda3", ear: "mane", namen: ["Leo", "Lea", "Luna", "Lino"],
      mag: { ding: "melone", farbe: "gelb" },
      isst: "Am liebsten Melone! Das weisst du doch aus dem Buch.",
      fakt: "Löwen leben in einer Familie, dem Rudel. Und ich döse sehr gern – bis zu 20 Stunden am Tag!" },
    mouse: { name: "Maus", der: "die Maus", coat: "#b0b3bd", inner: "#f7c9d4", ear: "big", namen: ["Mia", "Rosa", "Max", "Mo"],
      mag: { ding: "kaese", farbe: "rosa" },
      isst: "Körner und Samen – und ein Stückchen Käse.",
      fakt: "Meine Vorderzähne wachsen ein Leben lang nach. Darum nage ich so viel." },
    squirrel: { name: "Eichhörnchen", der: "das Eichhörnchen", coat: "#c9743a", inner: "#f2c9a6", ear: "tuft", namen: ["Nuki", "Elli", "Kiki", "Nico"],
      mag: { ding: "nuesse", farbe: "rot" },
      isst: "Nüsse! Im Herbst verstecke ich ganz viele für den Winter.",
      fakt: "Ich verstecke im Herbst Nüsse. Ich finde nicht alle wieder – daraus wachsen neue Bäume!" },
    ibex: { name: "Steinbock", der: "der Steinbock", coat: "#a99a86", inner: "#e9e2d6", ear: "horns", namen: ["Gian", "Mattia", "Sina", "Steffi"],
      mag: { ding: "klettern", farbe: "tuerkis" },
      isst: "Gras, Kräuter und Moos. Dafür klettere ich hoch in die Felsen.",
      fakt: "Ich wohne hoch oben in den Alpen. Meine Hufe halten an den Felsen fast wie Saugnäpfe. Ich bin das Wappentier von Graubünden!" },
    dog: { name: "Hund", der: "der Hund", coat: "#c49a6c", inner: "#f3e2c8", ear: "flop", namen: ["Bello", "Lumpi", "Nala", "Sammy"],
      mag: { ding: "koerbchen", farbe: "blau" },
      isst: "Einen Knochen zum Nagen – das ist das Beste!",
      fakt: "Ich kann viel besser riechen als die Menschen. Mit meiner Nase finde ich fast alles." },
    hedgehog: { name: "Igel", der: "der Igel", coat: "#8a6a4f", inner: "#e9d2b4", ear: "spikes", namen: ["Pieks", "Ida", "Igo", "Stupsi"],
      mag: { ding: "laub", farbe: "braun" },
      isst: "Käfer, Würmer und Schnecken.",
      fakt: "Ich habe ungefähr 7000 Stacheln. Im Winter schlafe ich in einem Laubhaufen." },
    cow: { name: "Kuh", der: "die Kuh", coat: "#fbf8f2", inner: "#ffc4d6", ear: "cow", namen: ["Lotti", "Rosi", "Frieda", "Fleck"],
      mag: { ding: "heu", farbe: "gruen" },
      isst: "Gras und Heu – und ich kaue alles zweimal.",
      fakt: "Ich gebe Milch. Daraus macht man Käse – in der Schweiz ganz viele Sorten!" },
    elephant: { name: "Elefant", der: "der Elefant", coat: "#a5adba", inner: "#d9dee6", ear: "elefant", namen: ["Emil", "Erna", "Tembo", "Mala"],
      mag: { ding: "dusche", farbe: "violett" },
      isst: "Gras, Blätter und Früchte – ganz, ganz viel davon!",
      fakt: "Mit meinem Rüssel kann ich trinken, duschen und sogar Hallo winken." },
  };
  const TIER_IDS = Object.keys(TIERE);

  // ---------------------------------------------------------------------------
  // Plaudern
  // ---------------------------------------------------------------------------
  // Was das Kind sagen kann: ein Bild und ein kurzer Satz. Was das Tier
  // antwortet, rechnet bau-stand.js aus Laune, Wünschen und Steckbrief aus.
  const PLAUDERN = [
    { id: "hallo", emoji: "👋", text: "Hallo!" },
    { id: "geht", emoji: "😊", text: "Wie geht es dir?" },
    { id: "wunsch", emoji: "🎁", text: "Was wünschst du dir?" },
    { id: "zimmer", emoji: "🏠", text: "Gefällt dir dein Zimmer?" },
    { id: "hunger", emoji: "🍎", text: "Was isst du gern?" },
    { id: "erzaehl", emoji: "📖", text: "Erzähl mir von dir!" },
    { id: "arbeit", emoji: "💼", text: "Was machst du hier?" },
    { id: "muede", emoji: "💤", text: "Bist du müde?" },
    { id: "witz", emoji: "😂", text: "Erzähl einen Witz!" },
    { id: "lied", emoji: "🎵", text: "Sing ein Lied!" },
    { id: "gern", emoji: "❤️", text: "Ich hab dich gern!" },
  ];

  const WITZE = [
    "Was ist grün und klopft an die Tür? Ein Klopfsalat!",
    "Was sagt der grosse Stift zum kleinen Stift? Wachs mal, Stift!",
    "Was ist orange und wandert durch den Wald? Eine Wanderine!",
    "Was ist braun, klebrig und läuft durch die Wüste? Ein Karamel!",
    "Was ist gelb und kann nicht schwimmen? Ein Bagger. Er hat nur einen Arm!",
    "Wie nennt man einen Bumerang, der nicht zurückkommt? Einen Stock!",
  ];

  const LIEDER = [
    "La la laaa! Ich wohne in einem schönen Haus! 🎵",
    "Tra-la-la, tra-la-li, heute bau ich mit dir! 🎶",
    "Dum di dum, die Ziegel kommen mit dem Zug! 🎵",
  ];

  window.LernappBauKatalog = {
    FARBEN, FARBE, FAMILIEN, MUSTER, BOEDEN, BODEN,
    HAEUSER, HAUS, RAEUME, RAEUME_LISTE,
    DING_WUENSCHE, HAUS_WUENSCHE, FREMD_WUENSCHE,
    TIERE, TIER_IDS, PLAUDERN, WITZE, LIEDER,
  };
})();
