(function () {
  const blocks = (...coords) => coords.map(([x, y, z, color]) => ({ x, y, z, ...(color ? { color } : {}) }));
  const face = (color, mark = "", rotation = 0) => ({ color, ...(mark ? { mark, rotation } : {}) });
  const faces = (front, right, top, left, back, bottom) => ({ front, right, top, left, back, bottom });
  const swapFaces = (source, first, second) => ({ ...source, [first]: source[second], [second]: source[first] });
  const turnFace = (source, name, rotation) => ({ ...source, [name]: { ...source[name], rotation } });
  const projection = (id, view, operation = null, cubes = null) => ({ id, kind: "projection", view, ...(operation ? { operation } : {}), ...(cubes ? { cubes } : {}) });
  const build = (id, operation = null, cubes = null) => ({ id, kind: "cubes", ...(operation ? { operation } : {}), ...(cubes ? { cubes } : {}) });
  const net = (id, netFaces) => ({ id, kind: "net", faces: netFaces });
  const level = (data) => data;

  const netEasyA = faces(face("rose"), face("sky"), face("sun"), face("mint"), face("violet"), face("orange"));
  const netEasyB = faces(face("mint"), face("orange"), face("sky"), face("rose"), face("sun"), face("violet"));
  const netMediumA = faces(face("sky", "L"), face("rose", "+"), face("sun", "T"), face("mint", "O"), face("violet", "X"), face("orange", "I"));
  const netMediumB = faces(face("mint", "O"), face("violet", "X"), face("sky", "L"), face("sun", "T"), face("rose", "+"), face("orange", "I"));
  const netHardA = faces(face("rose", "L"), face("sky", "T"), face("sun", "O"), face("mint", "+"), face("violet", "I"), face("orange", "X"));
  const netHardB = faces(face("sky", "F"), face("mint", "L"), face("orange", "T"), face("rose", "O"), face("violet", "X"), face("sun", "+"));
  const netExtremeA = faces(face("rose", "L", 0), face("sky", "T", 90), face("sun", "F", 0), face("mint", "+"), face("violet", "X"), face("orange", "I"));
  const netExtremeB = faces(face("mint", "F", 90), face("orange", "L", 180), face("sky", "T", 0), face("rose", "O"), face("violet", "X"), face("sun", "+"));

  window.SPATIAL_PUZZLES = [
    level({
      id: "spatial-easy-01",
      type: "viewMatch",
      difficulty: "easy",
      prompt: "Welche Ansicht sieht man von vorne?",
      description: "Ein kurzer Würfelbau mit zwei Ansichten.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]) },
      view: "front",
      options: [projection("A", "front"), projection("B", "front", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0]))],
      correctAnswer: "A",
      hint: "Zähle die Würfel, die unten von links nach rechts zu sehen sind.",
      explanation: "Von vorne sieht man unten zwei Würfel und links darüber einen Würfel.",
    }),
    level({
      id: "spatial-easy-02",
      type: "rotateBuild",
      difficulty: "easy",
      prompt: "Drehe den Würfelbau nach rechts.",
      description: "Eine einfache Drehung um eine Vierteldrehung.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 1, 0]) },
      operation: "yawRight",
      options: [build("A", "yawRight"), build("B", "yawLeft")],
      correctAnswer: "A",
      hint: "Der kurze Arm wandert beim Rechtsdrehen auf die andere Seite.",
      explanation: "Beim Drehen nach rechts bleibt die lange Reihe gleich lang, der einzelne Würfel steht danach vorne rechts.",
    }),
    level({
      id: "spatial-easy-03",
      type: "sameShape",
      difficulty: "easy",
      prompt: "Welcher Körper ist derselbe?",
      description: "Nur einer ist gedreht, der andere ist gespiegelt.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [1, 1, 1]) },
      options: [build("A", "yawLeft"), build("B", "mirrorX")],
      correctAnswer: "A",
      hint: "Achte darauf, auf welcher Ecke der obere Würfel sitzt.",
      explanation: "Der obere Würfel sitzt bei A auf derselben Ecke des kleinen Knicks. B ist gespiegelt.",
    }),
    level({
      id: "spatial-easy-04",
      type: "cubeNet",
      difficulty: "easy",
      prompt: "Welches Würfelnetz passt?",
      description: "Farben auf dem Würfelnetz vergleichen.",
      mainGraphic: { kind: "cube", faces: netEasyA },
      options: [net("A", netEasyA), net("B", swapFaces(netEasyA, "right", "top"))],
      correctAnswer: "A",
      hint: "Oben, vorne und rechts müssen wie am Würfel zusammenliegen.",
      explanation: "Im richtigen Netz liegen Gelb oben, Rosa vorne und Blau rechts direkt aneinander.",
    }),
    level({
      id: "spatial-easy-05",
      type: "viewMatch",
      difficulty: "easy",
      prompt: "Welche Ansicht sieht man von oben?",
      description: "Von oben zählt die Grundfläche.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [1, 0, 1]) },
      view: "top",
      options: [projection("A", "front", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 0, 1])), projection("B", "top")],
      correctAnswer: "B",
      hint: "Von oben sieht man, welche Plätze am Boden besetzt sind.",
      explanation: "Von oben sieht man eine kleine Ecke aus drei Feldern. Der obere Würfel ändert die Grundfläche nicht.",
    }),
    level({
      id: "spatial-easy-06",
      type: "rotateBuild",
      difficulty: "easy",
      prompt: "Drehe den Würfelbau nach links.",
      description: "Linksherum drehen und vergleichen.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [0, 1, 0], [1, 1, 0], [0, 1, 1]) },
      operation: "yawLeft",
      options: [build("A", "yawRight"), build("B", "yawLeft")],
      correctAnswer: "B",
      hint: "Der hohe Würfel bleibt auf demselben Ende des Knicks.",
      explanation: "Nach links gedreht zeigt der Knick zur anderen Seite, der zweite Würfel bleibt oben auf dem Endstück.",
    }),
    level({
      id: "spatial-easy-07",
      type: "viewMatch",
      difficulty: "easy",
      prompt: "Welche Ansicht sieht man von vorne?",
      description: "Ein langer Sockel mit einem Turm.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 0, 1]) },
      view: "front",
      options: [projection("A", "top"), projection("B", "front")],
      correctAnswer: "B",
      hint: "Der Turm steht ganz rechts.",
      explanation: "Von vorne sieht man unten drei Würfel und oben rechts einen zweiten Würfel.",
    }),
    level({
      id: "spatial-easy-08",
      type: "sameShape",
      difficulty: "easy",
      prompt: "Welcher Körper ist derselbe?",
      description: "Gedreht oder gespiegelt?",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [0, 1, 0], [1, 1, 0], [1, 0, 1]) },
      options: [build("A", null, blocks([0, 0, 0], [0, 1, 0], [1, 1, 0], [0, 0, 1])), build("B", "yawRight")],
      correctAnswer: "B",
      hint: "Der obere Würfel sitzt nicht auf dem Ende, sondern seitlich am Knick.",
      explanation: "B ist nur gedreht. Bei A liegt die hohe Ecke auf der falschen Seite.",
    }),
    level({
      id: "spatial-easy-09",
      type: "cubeNet",
      difficulty: "easy",
      prompt: "Welches Würfelnetz passt?",
      description: "Noch ein Würfelnetz mit Farben.",
      mainGraphic: { kind: "cube", faces: netEasyB },
      options: [net("A", swapFaces(netEasyB, "front", "top")), net("B", netEasyB)],
      correctAnswer: "B",
      hint: "Vergleiche die drei sichtbaren Farben.",
      explanation: "Im passenden Netz ist Grün vorne, Himmelblau oben und Violett rechts.",
    }),
    level({
      id: "spatial-easy-10",
      type: "rotateBuild",
      difficulty: "easy",
      prompt: "Kippe den Würfelbau nach vorne.",
      description: "Ein erster Kipp-Schritt.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [1, 0, 1]) },
      operation: "tiltForward",
      options: [build("A", "tiltForward"), build("B", "yawRight")],
      correctAnswer: "A",
      hint: "Beim Kippen wird Höhe zu Tiefe.",
      explanation: "Der hohe Würfel klappt nach vorne. Darum entsteht vorne ein zusätzliches Feld.",
    }),

    level({
      id: "spatial-medium-01",
      type: "viewMatch",
      difficulty: "medium",
      prompt: "Welche Ansicht sieht man von links?",
      description: "Drei mögliche Ansichten, eine passt.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 1, 0], [0, 1, 1]) },
      view: "left",
      options: [projection("A", "front"), projection("B", "left"), projection("C", "top", null, blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0]))],
      correctAnswer: "B",
      hint: "Von links sieht man Tiefe und Höhe, aber nicht die Breite.",
      explanation: "Von links sieht man hinten einen Turm aus zwei Würfeln und vorne einen einzelnen Würfel.",
    }),
    level({
      id: "spatial-medium-02",
      type: "rotateBuild",
      difficulty: "medium",
      prompt: "Drehe den Würfelbau nach rechts.",
      description: "Fünf Würfel mit einer klaren Ecke.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [1, 1, 1]) },
      operation: "yawRight",
      options: [build("A", "yawLeft"), build("B", "yawRight"), build("C", "mirrorX")],
      correctAnswer: "B",
      hint: "Der Turm bleibt auf dem mittleren Eckwürfel.",
      explanation: "Nach rechts gedreht liegt der lange Arm quer, der Turm steht weiterhin auf der Ecke.",
    }),
    level({
      id: "spatial-medium-03",
      type: "sameShape",
      difficulty: "medium",
      prompt: "Welcher Körper ist wirklich gleich?",
      description: "Ein gedrehter Körper zwischen zwei ähnlichen Formen.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [2, 1, 1]) },
      options: [build("A", "mirrorY"), build("B", "yawRight"), build("C", null, blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 0, 1], [2, 1, 0]))],
      correctAnswer: "B",
      hint: "Suche den Körper, bei dem der hohe Würfel am Ende der Treppe bleibt.",
      explanation: "B ist der gleiche Körper in einer anderen Richtung. A ist gespiegelt, C hat den oberen Würfel an der falschen Stelle.",
    }),
    level({
      id: "spatial-medium-04",
      type: "cubeNet",
      difficulty: "medium",
      prompt: "Welches Würfelnetz passt?",
      description: "Farben und Zeichen müssen stimmen.",
      mainGraphic: { kind: "cube", faces: netMediumA },
      options: [net("A", swapFaces(netMediumA, "front", "right")), net("B", netMediumA), net("C", swapFaces(netMediumA, "top", "right"))],
      correctAnswer: "B",
      hint: "Vorne ist L, oben ist T und rechts ist +.",
      explanation: "Nur B zeigt L vorne, T oben und + rechts in der richtigen Nachbarschaft.",
    }),
    level({
      id: "spatial-medium-05",
      type: "viewMatch",
      difficulty: "medium",
      prompt: "Welche Ansicht sieht man von oben?",
      description: "Ein verdeckter Würfel steckt unter einem Turm.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [1, 1, 0], [1, 1, 1]) },
      view: "top",
      options: [projection("A", "front", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 0, 1])), projection("B", "right"), projection("C", "top")],
      correctAnswer: "C",
      hint: "Von oben sieht ein Turm wie ein einzelnes Feld aus.",
      explanation: "Von oben sieht man vier besetzte Bodenplätze. Der zweite Würfel im Turm liegt direkt über einem schon sichtbaren Feld.",
    }),
    level({
      id: "spatial-medium-06",
      type: "rotateBuild",
      difficulty: "medium",
      prompt: "Drehe den Würfelbau nach links.",
      description: "Ein Tritt mit einem seitlichen Würfel.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [0, 1, 0], [1, 1, 0], [2, 1, 0], [2, 1, 1]) },
      operation: "yawLeft",
      options: [build("A", "yawLeft"), build("B", "yawRight"), build("C", "tiltForward")],
      correctAnswer: "A",
      hint: "Nur die Richtung ändert sich, die Höhe bleibt oben.",
      explanation: "A zeigt dieselbe Treppe nach links gedreht. Beim Kippen wäre die Höhe anders verteilt.",
    }),
    level({
      id: "spatial-medium-07",
      type: "viewMatch",
      difficulty: "medium",
      prompt: "Welche Ansicht sieht man von rechts?",
      description: "Breite und Tiefe sehen ähnlich aus.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [2, 1, 1]) },
      view: "right",
      options: [projection("A", "front"), projection("B", "right"), projection("C", "left")],
      correctAnswer: "B",
      hint: "Von rechts steht der Turm am hinteren Feld.",
      explanation: "Von rechts sieht man unten zwei Plätze in der Tiefe und hinten einen zweiten Würfel darüber.",
    }),
    level({
      id: "spatial-medium-08",
      type: "sameShape",
      difficulty: "medium",
      prompt: "Welcher Körper ist derselbe?",
      description: "Ein ähnlicher Körper hat einen Würfel zu viel an der Seite.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [1, 2, 0], [0, 2, 1]) },
      options: [build("A", "yawRight"), build("B", null, blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [1, 2, 0], [1, 2, 1])), build("C", "mirrorX")],
      correctAnswer: "A",
      hint: "Der obere Würfel sitzt am linken Ende der langen Seite.",
      explanation: "A ist nur gedreht. Bei B und C sitzt die obere Ecke an einer anderen Seite.",
    }),
    level({
      id: "spatial-medium-09",
      type: "cubeNet",
      difficulty: "medium",
      prompt: "Welches Würfelnetz passt?",
      description: "Zeichen und Farben vergleichen.",
      mainGraphic: { kind: "cube", faces: netMediumB },
      options: [net("A", netMediumB), net("B", swapFaces(netMediumB, "front", "top")), net("C", swapFaces(netMediumB, "right", "top"))],
      correctAnswer: "A",
      hint: "Vorne ist O, oben ist L und rechts ist X.",
      explanation: "Nur A legt O vorne, L oben und X rechts passend nebeneinander.",
    }),
    level({
      id: "spatial-medium-10",
      type: "rotateBuild",
      difficulty: "medium",
      prompt: "Kippe den Würfelbau nach vorne.",
      description: "Ein Kipp-Schritt mit fünf Würfeln.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [1, 0, 1]) },
      operation: "tiltForward",
      options: [build("A", "yawRight"), build("B", "tiltForward"), build("C", "yawLeft")],
      correctAnswer: "B",
      hint: "Beim Kippen entsteht aus der oberen Etage ein Feld nach vorne.",
      explanation: "B ist richtig: Die Höhe klappt nach vorne, während die seitliche Form erhalten bleibt.",
    }),

    level({
      id: "spatial-hard-01",
      type: "viewMatch",
      difficulty: "hard",
      prompt: "Welche Ansicht sieht man von vorne?",
      description: "Vier ähnliche Ansichten, nur eine passt.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 1, 0], [1, 1, 0], [1, 1, 1]) },
      view: "front",
      options: [projection("A", "left"), projection("B", "front"), projection("C", "top"), projection("D", "right")],
      correctAnswer: "B",
      hint: "Von vorne verschwindet die Tiefe, aber die Höhe bleibt sichtbar.",
      explanation: "Vorne sieht man unten drei Würfel breit und über der Mitte einen weiteren Würfel.",
    }),
    level({
      id: "spatial-hard-02",
      type: "rotateBuild",
      difficulty: "hard",
      prompt: "Drehe den Würfelbau nach rechts.",
      description: "Ein langer Arm und ein kurzer Turm.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [0, 1, 0], [2, 1, 1]) },
      operation: "yawRight",
      options: [build("A", "yawRight"), build("B", "yawLeft"), build("C", "mirrorY"), build("D", "tiltForward")],
      correctAnswer: "A",
      hint: "Die Höhe bleibt beim Drehen oben, sie kippt nicht um.",
      explanation: "A ist die Rechtsdrehung. D wäre gekippt, B dreht in die falsche Richtung.",
    }),
    level({
      id: "spatial-hard-03",
      type: "sameShape",
      difficulty: "hard",
      prompt: "Welcher Körper ist gleich?",
      description: "Spiegelbilder sind hier besonders ähnlich.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [2, 1, 1], [0, 0, 1]) },
      options: [build("A", "mirrorX"), build("B", "yawLeft"), build("C", null, blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [0, 1, 1], [0, 0, 1])), build("D", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 1, 0], [2, 1, 0], [1, 1, 1]))],
      correctAnswer: "B",
      hint: "Die beiden oberen Würfel sitzen an gegenüberliegenden Enden der Stufe.",
      explanation: "B ist derselbe Körper gedreht. Die anderen verändern die Handigkeit oder setzen einen oberen Würfel um.",
    }),
    level({
      id: "spatial-hard-04",
      type: "cubeNet",
      difficulty: "hard",
      prompt: "Welches Würfelnetz passt?",
      description: "Farben, Zeichen und Nachbarschaft prüfen.",
      mainGraphic: { kind: "cube", faces: netHardA },
      options: [net("A", swapFaces(netHardA, "right", "top")), net("B", swapFaces(netHardA, "front", "right")), net("C", netHardA), net("D", turnFace(netHardA, "top", 90))],
      correctAnswer: "C",
      hint: "Das O liegt oben, das L vorne und das T rechts.",
      explanation: "C passt: O oben berührt L vorne und T rechts. Die anderen tauschen sichtbare Flächen.",
    }),
    level({
      id: "spatial-hard-05",
      type: "viewMatch",
      difficulty: "hard",
      prompt: "Welche Ansicht sieht man von oben?",
      description: "Ein Turm verdeckt einen Würfel in der Grundfläche.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 1, 0], [0, 2, 0], [0, 2, 1], [1, 2, 0]) },
      view: "top",
      options: [projection("A", "front"), projection("B", "top"), projection("C", "left", null, blocks([0, 0, 0], [0, 1, 0], [0, 1, 1])), projection("D", "right")],
      correctAnswer: "B",
      hint: "Von oben zählt jeder belegte Platz nur einmal.",
      explanation: "Oben sieht man eine lange Ecke aus sechs Feldern. Der zweite Würfel im Turm macht kein neues Feld.",
    }),
    level({
      id: "spatial-hard-06",
      type: "rotateBuild",
      difficulty: "hard",
      prompt: "Kippe den Würfelbau nach vorne.",
      description: "Kippen ist keine Drehung auf dem Tisch.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [2, 1, 1], [1, 1, 1]) },
      operation: "tiltForward",
      options: [build("A", "yawRight"), build("B", "tiltBack"), build("C", "tiltForward"), build("D", "yawLeft")],
      correctAnswer: "C",
      hint: "Die obere Etage klappt nach vorne in die Tiefe.",
      explanation: "C zeigt das Kippen nach vorne. Bei einer Drehung bliebe die Höhe oben stehen.",
    }),
    level({
      id: "spatial-hard-07",
      type: "sameShape",
      difficulty: "hard",
      prompt: "Welcher Körper ist derselbe?",
      description: "Ein Knick mit zwei Höhen.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [0, 1, 0], [1, 1, 0], [2, 1, 0], [2, 0, 0], [2, 0, 1]) },
      options: [build("A", "mirrorX"), build("B", null, blocks([0, 0, 0], [0, 1, 0], [1, 1, 0], [2, 1, 0], [2, 0, 0], [0, 1, 1])), build("C", "yawRight"), build("D", "mirrorY")],
      correctAnswer: "C",
      hint: "Der Turm steht am Ende, das an den kurzen Rückweg anschließt.",
      explanation: "C ist eine echte Drehung. Bei den anderen wandert der Turm auf eine nicht passende Ecke.",
    }),
    level({
      id: "spatial-hard-08",
      type: "viewMatch",
      difficulty: "hard",
      prompt: "Welche Ansicht sieht man von rechts?",
      description: "Die Seitenansicht hat zwei Höhen.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [2, 2, 0], [1, 2, 0], [2, 2, 1]) },
      view: "right",
      options: [projection("A", "left"), projection("B", "front", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [1, 1, 1])), projection("C", "right"), projection("D", "top")],
      correctAnswer: "C",
      hint: "Von rechts sieht man die Tiefe von vorne nach hinten.",
      explanation: "Rechts sieht man drei Felder in der Tiefe und hinten einen zweiten Würfel oben.",
    }),
    level({
      id: "spatial-hard-09",
      type: "cubeNet",
      difficulty: "hard",
      prompt: "Welches Würfelnetz passt?",
      description: "Achte auf die Zeichen auf den sichtbaren Flächen.",
      mainGraphic: { kind: "cube", faces: netHardB },
      options: [net("A", turnFace(netHardB, "right", 90)), net("B", netHardB), net("C", swapFaces(netHardB, "front", "top")), net("D", swapFaces(netHardB, "right", "top"))],
      correctAnswer: "B",
      hint: "Vorne F, rechts L, oben T.",
      explanation: "B ordnet F, L und T genau so an, wie sie am Würfel zu sehen sind.",
    }),
    level({
      id: "spatial-hard-10",
      type: "rotateBuild",
      difficulty: "hard",
      prompt: "Drehe nach rechts und kippe dann nach vorne.",
      description: "Zwei Bewegungen nacheinander.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [2, 1, 1], [2, 2, 0]) },
      operation: ["yawRight", "tiltForward"],
      options: [build("A", ["yawRight", "tiltForward"]), build("B", ["yawLeft", "tiltForward"]), build("C", "yawRight"), build("D", "tiltForward")],
      correctAnswer: "A",
      hint: "Erst drehen, danach kippt die neue Form nach vorne.",
      explanation: "A folgt beiden Schritten. C zeigt nur die Drehung, D nur das Kippen.",
    }),

    level({
      id: "spatial-extreme-01",
      type: "viewMatch",
      difficulty: "extreme",
      prompt: "Welche Ansicht sieht man von links?",
      description: "Sehr ähnliche Seitenansichten.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 1, 0], [1, 1, 0], [1, 1, 1], [2, 2, 0], [2, 2, 1]) },
      view: "left",
      options: [projection("A", "left"), projection("B", "right"), projection("C", "front", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 1, 0], [2, 1, 1])), projection("D", "top")],
      correctAnswer: "A",
      hint: "Links sieht man die Tiefe mit zwei hohen Stellen.",
      explanation: "Von links sieht man unten drei Tiefenfelder; in der Mitte und hinten steht jeweils ein zweiter Würfel.",
    }),
    level({
      id: "spatial-extreme-02",
      type: "rotateBuild",
      difficulty: "extreme",
      prompt: "Drehe nach rechts und kippe dann nach vorne.",
      description: "Eine zusammengesetzte Bewegung.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [1, 1, 0], [1, 1, 1], [0, 2, 0]) },
      operation: ["yawRight", "tiltForward"],
      options: [build("A", ["yawRight", "tiltForward"]), build("B", ["yawLeft", "tiltForward"]), build("C", ["yawRight", "tiltBack"]), build("D", "yawRight")],
      correctAnswer: "A",
      hint: "Der zweite Schritt ist ein Kippen, keine zweite Drehung.",
      explanation: "A führt zuerst die Rechtsdrehung aus und klappt dann die neue obere Richtung nach vorne.",
    }),
    level({
      id: "spatial-extreme-03",
      type: "sameShape",
      difficulty: "extreme",
      prompt: "Welcher Körper ist wirklich derselbe?",
      description: "Ein gespiegelter Körper ist fast gleich.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [2, 2, 0], [2, 1, 1], [0, 0, 1]) },
      options: [build("A", "mirrorX"), build("B", "mirrorY"), build("C", "yawRight"), build("D", null, blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [2, 2, 0], [0, 0, 1], [0, 1, 1]))],
      correctAnswer: "C",
      hint: "Die beiden oberen Würfel sitzen an den Enden der Zickzack-Linie.",
      explanation: "C ist nur gedreht. A und B sind Spiegelbilder, D verändert einen oberen Würfel.",
    }),
    level({
      id: "spatial-extreme-04",
      type: "cubeNet",
      difficulty: "extreme",
      prompt: "Welches Würfelnetz passt?",
      description: "Auch die Richtung der Zeichen zählt.",
      mainGraphic: { kind: "cube", faces: netExtremeA },
      options: [net("A", turnFace(netExtremeA, "right", 0)), net("B", swapFaces(netExtremeA, "front", "top")), net("C", netExtremeA), net("D", turnFace(netExtremeA, "top", 180))],
      correctAnswer: "C",
      hint: "Vergleiche nicht nur die Farbe, sondern auch die Drehung der Buchstaben.",
      explanation: "C passt: L vorne, T rechts gedreht und F oben stehen genau wie am Würfel.",
    }),
    level({
      id: "spatial-extreme-05",
      type: "viewMatch",
      difficulty: "extreme",
      prompt: "Welche Ansicht sieht man von oben?",
      description: "Mehrere Felder liegen unter Türmen versteckt.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 1, 0], [0, 2, 0], [1, 2, 0], [1, 2, 1], [2, 2, 0]) },
      view: "top",
      options: [projection("A", "front"), projection("B", "left"), projection("C", "top"), projection("D", "right")],
      correctAnswer: "C",
      hint: "Von oben zählen Türme weiterhin als ein Feld.",
      explanation: "Von oben ergibt die Grundfläche ein U mit sieben Feldern. Der obere Würfel zählt nicht als neues Feld.",
    }),
    level({
      id: "spatial-extreme-06",
      type: "rotateBuild",
      difficulty: "extreme",
      prompt: "Drehe nach links und kippe dann nach hinten.",
      description: "Zwei Bewegungen in genauer Reihenfolge.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [0, 1, 0], [1, 1, 0], [2, 1, 0], [2, 0, 0], [2, 0, 1], [1, 2, 0]) },
      operation: ["yawLeft", "tiltBack"],
      options: [build("A", ["yawLeft", "tiltForward"]), build("B", ["yawRight", "tiltBack"]), build("C", ["yawLeft", "tiltBack"]), build("D", "yawLeft")],
      correctAnswer: "C",
      hint: "Nach dem Linksdrehen wird nach hinten gekippt.",
      explanation: "C zeigt beide Bewegungen in der richtigen Reihenfolge. D stoppt nach der Drehung.",
    }),
    level({
      id: "spatial-extreme-07",
      type: "sameShape",
      difficulty: "extreme",
      prompt: "Welcher Körper ist derselbe?",
      description: "Ein Würfelbau mit zwei versetzten Türmen.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [1, 1, 0], [1, 2, 0], [1, 2, 1], [0, 0, 1]) },
      options: [build("A", "yawLeft"), build("B", "mirrorX"), build("C", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [1, 1, 0], [1, 2, 0], [0, 2, 1], [0, 0, 1])), build("D", "mirrorY")],
      correctAnswer: "A",
      hint: "Die beiden oberen Würfel stehen nicht nebeneinander.",
      explanation: "A ist der gleiche Körper in anderer Lage. Die Spiegelungen setzen die beiden hohen Stellen falsch herum.",
    }),
    level({
      id: "spatial-extreme-08",
      type: "cubeNet",
      difficulty: "extreme",
      prompt: "Welches Würfelnetz passt?",
      description: "Zeichenrichtung und Nachbarschaft prüfen.",
      mainGraphic: { kind: "cube", faces: netExtremeB },
      options: [net("A", swapFaces(netExtremeB, "right", "top")), net("B", turnFace(netExtremeB, "front", 0)), net("C", netExtremeB), net("D", turnFace(netExtremeB, "right", 90))],
      correctAnswer: "C",
      hint: "Vorne ist das gedrehte F, rechts das gedrehte L, oben das T.",
      explanation: "C behält alle sichtbaren Flächen und ihre Drehung bei. Die anderen tauschen oder verdrehen sichtbare Zeichen.",
    }),
    level({
      id: "spatial-extreme-09",
      type: "viewMatch",
      difficulty: "extreme",
      prompt: "Welche Ansicht sieht man von vorne?",
      description: "Eine Ansicht mit versteckter Tiefe.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [3, 0, 0], [1, 1, 0], [2, 1, 0], [2, 1, 1], [3, 1, 1]) },
      view: "front",
      options: [projection("A", "front"), projection("B", "right"), projection("C", "left"), projection("D", "top")],
      correctAnswer: "A",
      hint: "Von vorne zählen die hinteren Würfel nur, wenn sie höher herausragen.",
      explanation: "Vorne sieht man unten vier Würfel. Über den zwei rechten Plätzen ragen je ein zweiter Würfel heraus.",
    }),
    level({
      id: "spatial-extreme-10",
      type: "rotateBuild",
      difficulty: "extreme",
      prompt: "Drehe zweimal nach rechts und kippe dann nach vorne.",
      description: "Drei Schritte nacheinander.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [2, 2, 0], [1, 2, 0], [1, 2, 1], [0, 1, 0]) },
      operation: ["yawRight", "yawRight", "tiltForward"],
      options: [build("A", ["yawRight", "tiltForward"]), build("B", ["yawRight", "yawRight", "tiltForward"]), build("C", ["yawLeft", "tiltForward"]), build("D", ["yawRight", "yawRight", "tiltBack"])],
      correctAnswer: "B",
      hint: "Zweimal rechts drehen ist eine halbe Drehung, erst danach wird gekippt.",
      explanation: "B macht alle drei Schritte: halbe Drehung nach rechts, dann nach vorne kippen.",
    }),
  ];
})();
