(function () {
  const blocks = (...coords) => coords.map(([x, y, z, color]) => ({ x, y, z, ...(color ? { color } : {}) }));
  const face = (color) => ({ color });
  const faces = (front, right, top, left, back, bottom) => ({ front, right, top, left, back, bottom });
  const swapFaces = (source, first, second) => ({ ...source, [first]: source[second], [second]: source[first] });
  const projection = (id, view, operation = null, cubes = null) => ({ id, kind: "projection", view, ...(operation ? { operation } : {}), ...(cubes ? { cubes } : {}) });
  const build = (id, operation = null, cubes = null) => ({ id, kind: "cubes", ...(operation ? { operation } : {}), ...(cubes ? { cubes } : {}) });
  const net = (id, netFaces, turns = 0) => ({ id, kind: "net", faces: netFaces, ...(turns ? { turns } : {}) });
  const level = (data) => data;

  const netEasyA = faces(face("rose"), face("sky"), face("sun"), face("mint"), face("violet"), face("orange"));
  const netEasyB = faces(face("mint"), face("orange"), face("sky"), face("rose"), face("sun"), face("violet"));
  const netMediumA = faces(face("sky"), face("rose"), face("sun"), face("mint"), face("violet"), face("orange"));
  const netMediumB = faces(face("mint"), face("violet"), face("sky"), face("sun"), face("rose"), face("orange"));
  const netHardA = faces(face("rose"), face("sky"), face("sun"), face("mint"), face("violet"), face("orange"));
  const netHardB = faces(face("sky"), face("mint"), face("orange"), face("rose"), face("violet"), face("sun"));
  const netExtremeA = faces(face("rose"), face("sky"), face("sun"), face("mint"), face("violet"), face("orange"));
  const netExtremeB = faces(face("mint"), face("orange"), face("sky"), face("rose"), face("violet"), face("sun"));

  window.SPATIAL_PUZZLES = [
    level({
      id: "spatial-easy-01",
      type: "viewMatch",
      difficulty: "easy",
      prompt: "Welche Figur passt?",
      description: "Ein kurzer Würfelbau mit zwei Ansichten.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]) },
      view: "front",
      options: [projection("A", "front"), projection("B", "front", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0]))],
      correctAnswer: "A",
      hint: "Zähle die Würfel, die unten von links nach rechts zu sehen sind.",
      explanation: "Von vorne sieht man unten zwei Würfel und links darüber einen Würfel.",
    }),
    level({
      id: "spatial-easy-02",
      type: "rotateBuild",
      difficulty: "easy",
      prompt: "Welche Figur ist dieselbe?",
      description: "Dieselbe Figur zwischen einer ähnlichen Form finden.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 1, 0]) },
      operation: "yawRight",
      options: [build("A", "yawRight"), build("B", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [1, 1, 0]))],
      correctAnswer: "A",
      hint: "Achte auf den kurzen Arm neben der langen Reihe.",
      explanation: "A zeigt denselben Körper. Bei B sitzt der kurze Arm an einer anderen Stelle.",
    }),
    level({
      id: "spatial-easy-03",
      type: "sameShape",
      difficulty: "easy",
      prompt: "Welche Figur ist dieselbe?",
      description: "Nur einer ist gedreht, der andere ist gespiegelt.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [1, 1, 1]) },
      options: [build("A", "yawLeft"), build("B", "mirrorX")],
      correctAnswer: "A",
      hint: "Achte darauf, auf welcher Ecke der obere Würfel sitzt.",
      explanation: "Der obere Würfel sitzt bei A auf derselben Ecke des kleinen Knicks. B ist gespiegelt.",
    }),
    level({
      id: "spatial-easy-04",
      type: "cubeNet",
      difficulty: "easy",
      prompt: "Welches Würfelnetz passt?",
      description: "Farben auf dem Würfelnetz vergleichen.",
      mainGraphic: { kind: "cube", faces: netEasyA },
      options: [net("A", netEasyA, 1), net("B", swapFaces(netEasyA, "right", "top"), 3)],
      correctAnswer: "A",
      hint: "Oben, vorne und rechts müssen wie am Würfel zusammenliegen.",
      explanation: "Im richtigen Netz liegen Gelb oben, Rosa vorne und Blau rechts direkt aneinander.",
    }),
    level({
      id: "spatial-easy-05",
      type: "viewMatch",
      difficulty: "easy",
      prompt: "Welche Figur passt?",
      description: "Von oben zählt die Grundfläche.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [1, 0, 1]) },
      view: "top",
      options: [projection("A", "front", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 0, 1])), projection("B", "top")],
      correctAnswer: "B",
      hint: "Von oben sieht man, welche Plätze am Boden besetzt sind.",
      explanation: "Von oben sieht man eine kleine Ecke aus drei Feldern. Der obere Würfel ändert die Grundfläche nicht.",
    }),
    level({
      id: "spatial-easy-06",
      type: "rotateBuild",
      difficulty: "easy",
      prompt: "Welche Figur ist dieselbe?",
      description: "Dieselbe Figur zwischen einer ähnlichen Form finden.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [0, 1, 0], [1, 1, 0], [0, 1, 1]) },
      operation: "yawLeft",
      options: [build("A", null, blocks([0, 0, 0], [0, 1, 0], [1, 1, 0], [1, 1, 1])), build("B", "yawLeft")],
      correctAnswer: "B",
      hint: "Der hohe Würfel bleibt auf demselben Ende des Knicks.",
      explanation: "B zeigt denselben Körper. Bei A sitzt die hohe Ecke an einer anderen Stelle.",
    }),
    level({
      id: "spatial-easy-07",
      type: "viewMatch",
      difficulty: "easy",
      prompt: "Welche Figur passt?",
      description: "Ein langer Sockel mit einem Turm.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 0, 1]) },
      view: "front",
      options: [projection("A", "top"), projection("B", "front")],
      correctAnswer: "B",
      hint: "Der Turm steht ganz rechts.",
      explanation: "Von vorne sieht man unten drei Würfel und oben rechts einen zweiten Würfel.",
    }),
    level({
      id: "spatial-easy-08",
      type: "sameShape",
      difficulty: "easy",
      prompt: "Welche Figur ist dieselbe?",
      description: "Gedreht oder gespiegelt?",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [0, 1, 0], [1, 1, 0], [1, 0, 1]) },
      options: [build("A", null, blocks([0, 0, 0], [0, 1, 0], [1, 1, 0], [0, 0, 1])), build("B", "yawRight")],
      correctAnswer: "B",
      hint: "Der obere Würfel sitzt nicht auf dem Ende, sondern seitlich am Knick.",
      explanation: "B ist nur gedreht. Bei A liegt die hohe Ecke auf der falschen Seite.",
    }),
    level({
      id: "spatial-easy-09",
      type: "cubeNet",
      difficulty: "easy",
      prompt: "Welches Würfelnetz passt?",
      description: "Noch ein Würfelnetz mit Farben.",
      mainGraphic: { kind: "cube", faces: netEasyB },
      options: [net("A", swapFaces(netEasyB, "front", "top"), 2), net("B", netEasyB, 1)],
      correctAnswer: "B",
      hint: "Vergleiche die drei sichtbaren Farben.",
      explanation: "Im passenden Netz ist Grün vorne, Himmelblau oben und Violett rechts.",
    }),
    level({
      id: "spatial-easy-10",
      type: "rotateBuild",
      difficulty: "easy",
      prompt: "Welche Figur ist dieselbe?",
      description: "Dieselbe Figur zwischen einer ähnlichen Form finden.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [1, 0, 1]) },
      operation: "tiltForward",
      options: [build("A", "tiltForward"), build("B", null, blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [1, 1, 1]))],
      correctAnswer: "A",
      hint: "Achte auf die Ecke mit dem oberen Würfel.",
      explanation: "A zeigt denselben Körper. Bei B liegt der obere Würfel im Vergleich zur Ecke falsch.",
    }),

    level({
      id: "spatial-medium-01",
      type: "viewMatch",
      difficulty: "medium",
      prompt: "Welche Figur passt?",
      description: "Drei mögliche Ansichten, eine passt.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 1, 0], [0, 1, 1]) },
      view: "left",
      options: [projection("A", "front"), projection("B", "left"), projection("C", "top", null, blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0]))],
      correctAnswer: "B",
      hint: "Von links sieht man Tiefe und Höhe, aber nicht die Breite.",
      explanation: "Von links sieht man hinten einen Turm aus zwei Würfeln und vorne einen einzelnen Würfel.",
    }),
    level({
      id: "spatial-medium-02",
      type: "rotateBuild",
      difficulty: "medium",
      prompt: "Welche Figur ist dieselbe?",
      description: "Fünf Würfel mit einer klaren Ecke.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [1, 1, 1]) },
      operation: "yawRight",
      options: [build("A", null, blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [0, 1, 1])), build("B", "yawRight"), build("C", "mirrorX")],
      correctAnswer: "B",
      hint: "Der Turm bleibt auf dem mittleren Eckwürfel.",
      explanation: "B zeigt denselben Körper. Bei den anderen sitzt der Turm im Vergleich zur Ecke falsch.",
    }),
    level({
      id: "spatial-medium-03",
      type: "sameShape",
      difficulty: "medium",
      prompt: "Welche Figur ist dieselbe?",
      description: "Ein gedrehter Körper zwischen zwei ähnlichen Formen.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [2, 1, 1]) },
      options: [build("A", "mirrorY"), build("B", "yawRight"), build("C", null, blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 0, 1], [2, 1, 0]))],
      correctAnswer: "B",
      hint: "Suche den Körper, bei dem der hohe Würfel am Ende der Treppe bleibt.",
      explanation: "B ist der gleiche Körper in einer anderen Richtung. A ist gespiegelt, C hat den oberen Würfel an der falschen Stelle.",
    }),
    level({
      id: "spatial-medium-04",
      type: "cubeNet",
      difficulty: "medium",
      prompt: "Welches Würfelnetz passt?",
      description: "Die Farben müssen stimmen.",
      mainGraphic: { kind: "cube", faces: netMediumA },
      options: [net("A", swapFaces(netMediumA, "front", "right"), 3), net("B", netMediumA, 1), net("C", swapFaces(netMediumA, "top", "right"), 2)],
      correctAnswer: "B",
      hint: "Vergleiche die drei sichtbaren Farben am Würfel.",
      explanation: "Nur B legt die sichtbaren Farben in der richtigen Nachbarschaft aneinander.",
    }),
    level({
      id: "spatial-medium-05",
      type: "viewMatch",
      difficulty: "medium",
      prompt: "Welche Figur passt?",
      description: "Ein verdeckter Würfel steckt unter einem Turm.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [1, 1, 0], [1, 1, 1]) },
      view: "top",
      options: [projection("A", "front", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 0, 1])), projection("B", "right"), projection("C", "top")],
      correctAnswer: "C",
      hint: "Von oben sieht ein Turm wie ein einzelnes Feld aus.",
      explanation: "Von oben sieht man vier besetzte Bodenplätze. Der zweite Würfel im Turm liegt direkt über einem schon sichtbaren Feld.",
    }),
    level({
      id: "spatial-medium-06",
      type: "rotateBuild",
      difficulty: "medium",
      prompt: "Welche Figur ist dieselbe?",
      description: "Ein Tritt mit einem seitlichen Würfel.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [0, 1, 0], [1, 1, 0], [2, 1, 0], [2, 1, 1]) },
      operation: "yawLeft",
      options: [build("A", "yawLeft"), build("B", null, blocks([0, 0, 0], [0, 1, 0], [1, 1, 0], [2, 1, 0], [0, 1, 1])), build("C", null, blocks([0, 0, 0], [0, 1, 0], [1, 1, 0], [2, 1, 0], [1, 1, 1]))],
      correctAnswer: "A",
      hint: "Die Höhe bleibt auf dem Ende der Treppe.",
      explanation: "A zeigt denselben Körper. Bei den anderen sitzt die Höhe nicht auf dem passenden Ende.",
    }),
    level({
      id: "spatial-medium-07",
      type: "viewMatch",
      difficulty: "medium",
      prompt: "Welche Figur passt?",
      description: "Breite und Tiefe sehen ähnlich aus.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [2, 1, 1]) },
      view: "right",
      options: [projection("A", "front"), projection("B", "right"), projection("C", "left")],
      correctAnswer: "B",
      hint: "Von rechts steht der Turm am hinteren Feld.",
      explanation: "Von rechts sieht man unten zwei Plätze in der Tiefe und hinten einen zweiten Würfel darüber.",
    }),
    level({
      id: "spatial-medium-08",
      type: "sameShape",
      difficulty: "medium",
      prompt: "Welche Figur ist dieselbe?",
      description: "Ein ähnlicher Körper hat einen Würfel zu viel an der Seite.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [1, 2, 0], [0, 2, 1]) },
      options: [build("A", "yawRight"), build("B", null, blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [1, 2, 0], [1, 2, 1])), build("C", "mirrorX")],
      correctAnswer: "A",
      hint: "Der obere Würfel sitzt am linken Ende der langen Seite.",
      explanation: "A ist nur gedreht. Bei B und C sitzt die obere Ecke an einer anderen Seite.",
    }),
    level({
      id: "spatial-medium-09",
      type: "cubeNet",
      difficulty: "medium",
      prompt: "Welches Würfelnetz passt?",
      description: "Farben vergleichen.",
      mainGraphic: { kind: "cube", faces: netMediumB },
      options: [net("A", netMediumB, 2), net("B", swapFaces(netMediumB, "front", "top"), 1), net("C", swapFaces(netMediumB, "right", "top"), 3)],
      correctAnswer: "A",
      hint: "Vergleiche die drei sichtbaren Farben am Würfel.",
      explanation: "Nur A legt die sichtbaren Farben passend nebeneinander.",
    }),
    level({
      id: "spatial-medium-10",
      type: "rotateBuild",
      difficulty: "medium",
      prompt: "Welche Figur ist dieselbe?",
      description: "Dieselbe Figur zwischen ähnlichen Formen finden.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [1, 0, 1]) },
      operation: "tiltForward",
      options: [build("A", null, blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [0, 0, 1])), build("B", "tiltForward"), build("C", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [1, 1, 0], [1, 0, 1]))],
      correctAnswer: "B",
      hint: "Der obere Würfel sitzt am Knick, nicht an einem Ende.",
      explanation: "B zeigt denselben Körper. Die anderen setzen den oberen Würfel auf eine andere Stelle.",
    }),

    level({
      id: "spatial-hard-01",
      type: "viewMatch",
      difficulty: "hard",
      prompt: "Welche Figur passt?",
      description: "Vier ähnliche Ansichten, nur eine passt.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 1, 0], [1, 1, 0], [1, 1, 1]) },
      view: "front",
      options: [projection("A", "left"), projection("B", "front"), projection("C", "top"), projection("D", "right")],
      correctAnswer: "B",
      hint: "Von vorne verschwindet die Tiefe, aber die Höhe bleibt sichtbar.",
      explanation: "Vorne sieht man unten drei Würfel breit und über der Mitte einen weiteren Würfel.",
    }),
    level({
      id: "spatial-hard-02",
      type: "rotateBuild",
      difficulty: "hard",
      prompt: "Welche Figur ist dieselbe?",
      description: "Ein langer Arm und ein kurzer Turm.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [0, 1, 0], [2, 1, 1]) },
      operation: "yawRight",
      options: [build("A", "yawRight"), build("B", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [0, 1, 0], [0, 1, 1])), build("C", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [0, 1, 0], [1, 0, 1])), build("D", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [0, 1, 0], [1, 1, 1]))],
      correctAnswer: "A",
      hint: "Der Turm sitzt am Ende des kurzen Arms.",
      explanation: "A zeigt denselben Körper. Bei den anderen sitzt der Turm nicht an der passenden Ecke.",
    }),
    level({
      id: "spatial-hard-03",
      type: "sameShape",
      difficulty: "hard",
      prompt: "Welche Figur ist dieselbe?",
      description: "Spiegelbilder sind hier besonders ähnlich.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [2, 1, 1], [0, 0, 1]) },
      options: [build("A", "mirrorX"), build("B", "yawLeft"), build("C", null, blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [0, 1, 1], [0, 0, 1])), build("D", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 1, 0], [2, 1, 0], [1, 1, 1]))],
      correctAnswer: "B",
      hint: "Die beiden oberen Würfel sitzen an gegenüberliegenden Enden der Stufe.",
      explanation: "B ist derselbe Körper gedreht. Die anderen verändern die Handigkeit oder setzen einen oberen Würfel um.",
    }),
    level({
      id: "spatial-hard-04",
      type: "cubeNet",
      difficulty: "hard",
      prompt: "Welches Würfelnetz passt?",
      description: "Farben und Nachbarschaft prüfen.",
      mainGraphic: { kind: "cube", faces: netHardA },
      options: [net("A", swapFaces(netHardA, "right", "top"), 3), net("B", swapFaces(netHardA, "front", "right"), 1), net("C", netHardA, 2), net("D", swapFaces(netHardA, "front", "top"))],
      correctAnswer: "C",
      hint: "Vergleiche die drei sichtbaren Farben am Würfel.",
      explanation: "C passt: Die sichtbaren Farben berühren sich im Netz so wie am Würfel.",
    }),
    level({
      id: "spatial-hard-05",
      type: "viewMatch",
      difficulty: "hard",
      prompt: "Welche Figur passt?",
      description: "Ein Turm verdeckt einen Würfel in der Grundfläche.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 1, 0], [0, 2, 0], [0, 2, 1], [1, 2, 0]) },
      view: "top",
      options: [projection("A", "front"), projection("B", "top"), projection("C", "left", null, blocks([0, 0, 0], [0, 1, 0], [0, 1, 1])), projection("D", "right")],
      correctAnswer: "B",
      hint: "Von oben zählt jeder belegte Platz nur einmal.",
      explanation: "Oben sieht man eine lange Ecke aus sechs Feldern. Der zweite Würfel im Turm macht kein neues Feld.",
    }),
    level({
      id: "spatial-hard-06",
      type: "rotateBuild",
      difficulty: "hard",
      prompt: "Welche Figur ist dieselbe?",
      description: "Dieselbe Figur zwischen ähnlichen Formen finden.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [2, 1, 1], [1, 1, 1]) },
      operation: "tiltForward",
      options: [build("A", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [2, 1, 1], [0, 1, 1])), build("B", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [2, 1, 1], [1, 0, 1])), build("C", "tiltForward"), build("D", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [1, 1, 1], [0, 1, 1]))],
      correctAnswer: "C",
      hint: "Die beiden oberen Würfel bleiben nebeneinander.",
      explanation: "C zeigt denselben Körper. Die anderen verschieben eine obere Ecke.",
    }),
    level({
      id: "spatial-hard-07",
      type: "sameShape",
      difficulty: "hard",
      prompt: "Welche Figur ist dieselbe?",
      description: "Ein Knick mit zwei Höhen.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [0, 1, 0], [1, 1, 0], [2, 1, 0], [2, 0, 0], [2, 0, 1]) },
      options: [build("A", "mirrorX"), build("B", null, blocks([0, 0, 0], [0, 1, 0], [1, 1, 0], [2, 1, 0], [2, 0, 0], [0, 1, 1])), build("C", "yawRight"), build("D", null, blocks([0, 0, 0], [0, 1, 0], [1, 1, 0], [2, 1, 0], [2, 0, 0], [1, 1, 1]))],
      correctAnswer: "C",
      hint: "Der Turm steht am Ende, das an den kurzen Rückweg anschließt.",
      explanation: "C ist eine echte Drehung. Bei den anderen wandert der Turm auf eine nicht passende Ecke.",
    }),
    level({
      id: "spatial-hard-08",
      type: "viewMatch",
      difficulty: "hard",
      prompt: "Welche Figur passt?",
      description: "Die Seitenansicht hat zwei Höhen.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [2, 2, 0], [1, 2, 0], [2, 2, 1]) },
      view: "right",
      options: [projection("A", "left"), projection("B", "front", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [1, 1, 1])), projection("C", "right"), projection("D", "top")],
      correctAnswer: "C",
      hint: "Von rechts sieht man die Tiefe von vorne nach hinten.",
      explanation: "Rechts sieht man drei Felder in der Tiefe und hinten einen zweiten Würfel oben.",
    }),
    level({
      id: "spatial-hard-09",
      type: "cubeNet",
      difficulty: "hard",
      prompt: "Welches Würfelnetz passt?",
      description: "Achte auf die Farben auf den sichtbaren Flächen.",
      mainGraphic: { kind: "cube", faces: netHardB },
      options: [net("A", swapFaces(netHardB, "front", "right"), 1), net("B", netHardB, 3), net("C", swapFaces(netHardB, "front", "top"), 2), net("D", swapFaces(netHardB, "right", "top"))],
      correctAnswer: "B",
      hint: "Vergleiche die drei sichtbaren Farben am Würfel.",
      explanation: "B ordnet die sichtbaren Farben genau so an, wie sie am Würfel zu sehen sind.",
    }),
    level({
      id: "spatial-hard-10",
      type: "rotateBuild",
      difficulty: "hard",
      prompt: "Welche Figur ist dieselbe?",
      description: "Dieselbe Figur zwischen ähnlichen Formen finden.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [2, 1, 1], [2, 2, 0]) },
      operation: ["yawRight", "tiltForward"],
      options: [build("A", ["yawRight", "tiltForward"]), build("B", null, blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [2, 1, 1], [0, 1, 0])), build("C", null, blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [0, 1, 1], [2, 2, 0])), build("D", null, blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [1, 1, 1], [2, 2, 0]))],
      correctAnswer: "A",
      hint: "Der obere Würfel bleibt am Ende der Stufe.",
      explanation: "A zeigt denselben Körper. Die anderen verändern eine Ecke oder den oberen Würfel.",
    }),

    level({
      id: "spatial-extreme-01",
      type: "viewMatch",
      difficulty: "extreme",
      prompt: "Welche Figur passt?",
      description: "Sehr ähnliche Seitenansichten.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 1, 0], [1, 1, 0], [1, 1, 1], [2, 2, 0], [2, 2, 1]) },
      view: "left",
      options: [projection("A", "left"), projection("B", "right"), projection("C", "front", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 1, 0], [2, 1, 1])), projection("D", "top")],
      correctAnswer: "A",
      hint: "Links sieht man die Tiefe mit zwei hohen Stellen.",
      explanation: "Von links sieht man unten drei Tiefenfelder; in der Mitte und hinten steht jeweils ein zweiter Würfel.",
    }),
    level({
      id: "spatial-extreme-02",
      type: "rotateBuild",
      difficulty: "extreme",
      prompt: "Welche Figur ist dieselbe?",
      description: "Dieselbe Figur zwischen ähnlichen Formen finden.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [1, 1, 0], [1, 1, 1], [0, 2, 0]) },
      operation: ["yawRight", "tiltForward"],
      options: [build("A", ["yawRight", "tiltForward"]), build("B", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [1, 1, 0], [0, 1, 1], [0, 2, 0])), build("C", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [1, 1, 0], [2, 1, 1], [0, 2, 0])), build("D", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [1, 1, 0], [1, 0, 1], [0, 2, 0]))],
      correctAnswer: "A",
      hint: "Der obere Würfel sitzt auf der inneren Ecke.",
      explanation: "A zeigt denselben Körper. Bei den anderen wandert der obere Würfel auf eine andere Stelle.",
    }),
    level({
      id: "spatial-extreme-03",
      type: "sameShape",
      difficulty: "extreme",
      prompt: "Welche Figur ist dieselbe?",
      description: "Ein gespiegelter Körper ist fast gleich.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [2, 2, 0], [2, 1, 1], [0, 0, 1]) },
      options: [build("A", "mirrorX"), build("B", null, blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [2, 2, 0], [2, 1, 1], [1, 0, 1])), build("C", "yawRight"), build("D", null, blocks([0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [2, 2, 0], [0, 0, 1], [0, 1, 1]))],
      correctAnswer: "C",
      hint: "Die beiden oberen Würfel sitzen an den Enden der Zickzack-Linie.",
      explanation: "C ist nur gedreht. A und B sind Spiegelbilder, D verändert einen oberen Würfel.",
    }),
    level({
      id: "spatial-extreme-04",
      type: "cubeNet",
      difficulty: "extreme",
      prompt: "Welches Würfelnetz passt?",
      description: "Die Farben müssen stimmen.",
      mainGraphic: { kind: "cube", faces: netExtremeA },
      options: [net("A", swapFaces(netExtremeA, "right", "top"), 1), net("B", swapFaces(netExtremeA, "front", "top"), 3), net("C", netExtremeA, 2), net("D", swapFaces(netExtremeA, "front", "right"))],
      correctAnswer: "C",
      hint: "Vergleiche die drei sichtbaren Farben am Würfel.",
      explanation: "C passt: Die drei sichtbaren Farben stehen im Netz in der richtigen Nachbarschaft.",
    }),
    level({
      id: "spatial-extreme-05",
      type: "viewMatch",
      difficulty: "extreme",
      prompt: "Welche Figur passt?",
      description: "Mehrere Felder liegen unter Türmen versteckt.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 1, 0], [0, 2, 0], [1, 2, 0], [1, 2, 1], [2, 2, 0]) },
      view: "top",
      options: [projection("A", "front"), projection("B", "left"), projection("C", "top"), projection("D", "right")],
      correctAnswer: "C",
      hint: "Von oben zählen Türme weiterhin als ein Feld.",
      explanation: "Von oben ergibt die Grundfläche ein U mit sieben Feldern. Der obere Würfel zählt nicht als neues Feld.",
    }),
    level({
      id: "spatial-extreme-06",
      type: "rotateBuild",
      difficulty: "extreme",
      prompt: "Welche Figur ist dieselbe?",
      description: "Dieselbe Figur zwischen ähnlichen Formen finden.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [0, 1, 0], [1, 1, 0], [2, 1, 0], [2, 0, 0], [2, 0, 1], [1, 2, 0]) },
      operation: ["yawLeft", "tiltBack"],
      options: [build("A", null, blocks([0, 0, 0], [0, 1, 0], [1, 1, 0], [2, 1, 0], [2, 0, 0], [0, 0, 1], [1, 2, 0])), build("B", null, blocks([0, 0, 0], [0, 1, 0], [1, 1, 0], [2, 1, 0], [2, 0, 0], [2, 1, 1], [1, 2, 0])), build("C", ["yawLeft", "tiltBack"]), build("D", null, blocks([0, 0, 0], [0, 1, 0], [1, 1, 0], [2, 1, 0], [2, 0, 0], [1, 1, 1], [1, 2, 0]))],
      correctAnswer: "C",
      hint: "Der obere Würfel sitzt am Ende des kurzen Rückwegs.",
      explanation: "C zeigt denselben Körper. Die anderen setzen die hohe Stelle um.",
    }),
    level({
      id: "spatial-extreme-07",
      type: "sameShape",
      difficulty: "extreme",
      prompt: "Welche Figur ist dieselbe?",
      description: "Ein Würfelbau mit zwei versetzten Türmen.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [1, 1, 0], [1, 2, 0], [1, 2, 1], [0, 0, 1]) },
      options: [build("A", "yawLeft"), build("B", "mirrorX"), build("C", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [1, 1, 0], [1, 2, 0], [0, 2, 1], [0, 0, 1])), build("D", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [1, 1, 0], [1, 2, 0], [1, 1, 1], [0, 0, 1]))],
      correctAnswer: "A",
      hint: "Die beiden oberen Würfel stehen nicht nebeneinander.",
      explanation: "A ist der gleiche Körper in anderer Lage. Die Spiegelungen setzen die beiden hohen Stellen falsch herum.",
    }),
    level({
      id: "spatial-extreme-08",
      type: "cubeNet",
      difficulty: "extreme",
      prompt: "Welches Würfelnetz passt?",
      description: "Farben und Nachbarschaft prüfen.",
      mainGraphic: { kind: "cube", faces: netExtremeB },
      options: [net("A", swapFaces(netExtremeB, "right", "top"), 3), net("B", swapFaces(netExtremeB, "front", "top"), 1), net("C", netExtremeB, 2), net("D", swapFaces(netExtremeB, "front", "right"))],
      correctAnswer: "C",
      hint: "Vergleiche die drei sichtbaren Farben am Würfel.",
      explanation: "C behält alle sichtbaren Farben in der richtigen Nachbarschaft bei. Die anderen tauschen sichtbare Flächen.",
    }),
    level({
      id: "spatial-extreme-09",
      type: "viewMatch",
      difficulty: "extreme",
      prompt: "Welche Figur passt?",
      description: "Eine Ansicht mit versteckter Tiefe.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [3, 0, 0], [1, 1, 0], [2, 1, 0], [2, 1, 1], [3, 1, 1]) },
      view: "front",
      options: [projection("A", "front"), projection("B", "right"), projection("C", "left"), projection("D", "top")],
      correctAnswer: "A",
      hint: "Von vorne zählen die hinteren Würfel nur, wenn sie höher herausragen.",
      explanation: "Vorne sieht man unten vier Würfel. Über den zwei rechten Plätzen ragen je ein zweiter Würfel heraus.",
    }),
    level({
      id: "spatial-extreme-10",
      type: "rotateBuild",
      difficulty: "extreme",
      prompt: "Welche Figur ist dieselbe?",
      description: "Dieselbe Figur zwischen ähnlichen Formen finden.",
      mainGraphic: { kind: "cubes", cubes: blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [2, 2, 0], [1, 2, 0], [1, 2, 1], [0, 1, 0]) },
      operation: ["yawRight", "yawRight", "tiltForward"],
      options: [build("A", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [2, 2, 0], [1, 2, 0], [0, 2, 1], [0, 1, 0])), build("B", ["yawRight", "yawRight", "tiltForward"]), build("C", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [2, 2, 0], [1, 2, 0], [2, 2, 1], [0, 1, 0])), build("D", null, blocks([0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [2, 2, 0], [1, 2, 0], [1, 1, 1], [0, 1, 0]))],
      correctAnswer: "B",
      hint: "Der obere Würfel bleibt auf der inneren Ecke des langen Wegs.",
      explanation: "B zeigt denselben Körper. Die anderen verändern die hohe Ecke.",
    }),
  ];
})();
